package game2peer.mybatis.dao;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import game2peer.mybatis.domain.BusiUserAccountDetails;
import game2peer.mybatis.domain.BusiUserAccountDetailsExample;

@Mapper
public interface BusiUserAccountDetailsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table busi_user_account_details
     *
     * @mbg.generated Thu May 18 20:46:39 CST 2017
     */
    long countByExample(BusiUserAccountDetailsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table busi_user_account_details
     *
     * @mbg.generated Thu May 18 20:46:39 CST 2017
     */
    int deleteByExample(BusiUserAccountDetailsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table busi_user_account_details
     *
     * @mbg.generated Thu May 18 20:46:39 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table busi_user_account_details
     *
     * @mbg.generated Thu May 18 20:46:39 CST 2017
     */
    int insert(BusiUserAccountDetails record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table busi_user_account_details
     *
     * @mbg.generated Thu May 18 20:46:39 CST 2017
     */
    int insertSelective(BusiUserAccountDetails record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table busi_user_account_details
     *
     * @mbg.generated Thu May 18 20:46:39 CST 2017
     */
    List<BusiUserAccountDetails> selectByExample(BusiUserAccountDetailsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table busi_user_account_details
     *
     * @mbg.generated Thu May 18 20:46:39 CST 2017
     */
    BusiUserAccountDetails selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table busi_user_account_details
     *
     * @mbg.generated Thu May 18 20:46:39 CST 2017
     */
    int updateByExampleSelective(@Param("record") BusiUserAccountDetails record, @Param("example") BusiUserAccountDetailsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table busi_user_account_details
     *
     * @mbg.generated Thu May 18 20:46:39 CST 2017
     */
    int updateByExample(@Param("record") BusiUserAccountDetails record, @Param("example") BusiUserAccountDetailsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table busi_user_account_details
     *
     * @mbg.generated Thu May 18 20:46:39 CST 2017
     */
    int updateByPrimaryKeySelective(BusiUserAccountDetails record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table busi_user_account_details
     *
     * @mbg.generated Thu May 18 20:46:39 CST 2017
     */
    int updateByPrimaryKey(BusiUserAccountDetails record);
}