package game2peer.mybatis.dao;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import game2peer.mybatis.domain.BusiGameDownload;
import game2peer.mybatis.domain.BusiGameDownloadExample;
import game2peer.mybatis.domain.BusiGameDownloadKey;

@Mapper
public interface BusiGameDownloadMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table busi_game_download
     *
     * @mbg.generated Mon May 15 08:36:44 CST 2017
     */
    long countByExample(BusiGameDownloadExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table busi_game_download
     *
     * @mbg.generated Mon May 15 08:36:44 CST 2017
     */
    int deleteByExample(BusiGameDownloadExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table busi_game_download
     *
     * @mbg.generated Mon May 15 08:36:44 CST 2017
     */
    int deleteByPrimaryKey(BusiGameDownloadKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table busi_game_download
     *
     * @mbg.generated Mon May 15 08:36:44 CST 2017
     */
    int insert(BusiGameDownload record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table busi_game_download
     *
     * @mbg.generated Mon May 15 08:36:44 CST 2017
     */
    int insertSelective(BusiGameDownload record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table busi_game_download
     *
     * @mbg.generated Mon May 15 08:36:44 CST 2017
     */
    List<BusiGameDownload> selectByExample(BusiGameDownloadExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table busi_game_download
     *
     * @mbg.generated Mon May 15 08:36:44 CST 2017
     */
    BusiGameDownload selectByPrimaryKey(BusiGameDownloadKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table busi_game_download
     *
     * @mbg.generated Mon May 15 08:36:44 CST 2017
     */
    int updateByExampleSelective(@Param("record") BusiGameDownload record, @Param("example") BusiGameDownloadExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table busi_game_download
     *
     * @mbg.generated Mon May 15 08:36:44 CST 2017
     */
    int updateByExample(@Param("record") BusiGameDownload record, @Param("example") BusiGameDownloadExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table busi_game_download
     *
     * @mbg.generated Mon May 15 08:36:44 CST 2017
     */
    int updateByPrimaryKeySelective(BusiGameDownload record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table busi_game_download
     *
     * @mbg.generated Mon May 15 08:36:44 CST 2017
     */
    int updateByPrimaryKey(BusiGameDownload record);
}