package game2peer.mybatis.dao;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import game2peer.mybatis.domain.BusiUserBankaccount;
import game2peer.mybatis.domain.BusiUserBankaccountExample;

@Mapper
public interface BusiUserBankaccountMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table busi_user_bankaccount
     *
     * @mbg.generated Fri May 19 09:10:27 CST 2017
     */
    long countByExample(BusiUserBankaccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table busi_user_bankaccount
     *
     * @mbg.generated Fri May 19 09:10:27 CST 2017
     */
    int deleteByExample(BusiUserBankaccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table busi_user_bankaccount
     *
     * @mbg.generated Fri May 19 09:10:27 CST 2017
     */
    int deleteByPrimaryKey(String userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table busi_user_bankaccount
     *
     * @mbg.generated Fri May 19 09:10:27 CST 2017
     */
    int insert(BusiUserBankaccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table busi_user_bankaccount
     *
     * @mbg.generated Fri May 19 09:10:27 CST 2017
     */
    int insertSelective(BusiUserBankaccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table busi_user_bankaccount
     *
     * @mbg.generated Fri May 19 09:10:27 CST 2017
     */
    List<BusiUserBankaccount> selectByExample(BusiUserBankaccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table busi_user_bankaccount
     *
     * @mbg.generated Fri May 19 09:10:27 CST 2017
     */
    BusiUserBankaccount selectByPrimaryKey(String userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table busi_user_bankaccount
     *
     * @mbg.generated Fri May 19 09:10:27 CST 2017
     */
    int updateByExampleSelective(@Param("record") BusiUserBankaccount record, @Param("example") BusiUserBankaccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table busi_user_bankaccount
     *
     * @mbg.generated Fri May 19 09:10:27 CST 2017
     */
    int updateByExample(@Param("record") BusiUserBankaccount record, @Param("example") BusiUserBankaccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table busi_user_bankaccount
     *
     * @mbg.generated Fri May 19 09:10:27 CST 2017
     */
    int updateByPrimaryKeySelective(BusiUserBankaccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table busi_user_bankaccount
     *
     * @mbg.generated Fri May 19 09:10:27 CST 2017
     */
    int updateByPrimaryKey(BusiUserBankaccount record);
}