package game2peer.mybatis.dao;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import game2peer.mybatis.domain.BusiGameLog;
import game2peer.mybatis.domain.BusiGameLogExample;

@Mapper
public interface BusiGameLogMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table busi_game_log
	 * @mbg.generated  Tue May 09 16:05:21 CST 2017
	 */
	long countByExample(BusiGameLogExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table busi_game_log
	 * @mbg.generated  Tue May 09 16:05:21 CST 2017
	 */
	int deleteByExample(BusiGameLogExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table busi_game_log
	 * @mbg.generated  Tue May 09 16:05:21 CST 2017
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table busi_game_log
	 * @mbg.generated  Tue May 09 16:05:21 CST 2017
	 */
	int insert(BusiGameLog record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table busi_game_log
	 * @mbg.generated  Tue May 09 16:05:21 CST 2017
	 */
	int insertSelective(BusiGameLog record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table busi_game_log
	 * @mbg.generated  Tue May 09 16:05:21 CST 2017
	 */
	List<BusiGameLog> selectByExample(BusiGameLogExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table busi_game_log
	 * @mbg.generated  Tue May 09 16:05:21 CST 2017
	 */
	BusiGameLog selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table busi_game_log
	 * @mbg.generated  Tue May 09 16:05:21 CST 2017
	 */
	int updateByExampleSelective(@Param("record") BusiGameLog record, @Param("example") BusiGameLogExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table busi_game_log
	 * @mbg.generated  Tue May 09 16:05:21 CST 2017
	 */
	int updateByExample(@Param("record") BusiGameLog record, @Param("example") BusiGameLogExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table busi_game_log
	 * @mbg.generated  Tue May 09 16:05:21 CST 2017
	 */
	int updateByPrimaryKeySelective(BusiGameLog record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table busi_game_log
	 * @mbg.generated  Tue May 09 16:05:21 CST 2017
	 */
	int updateByPrimaryKey(BusiGameLog record);
}