package game2peer.mybatis.dao;

import game2peer.mybatis.domain.BusiGamePayment;
import game2peer.mybatis.domain.BusiGamePaymentExample;
import game2peer.mybatis.domain.BusiGamePaymentKey;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface BusiGamePaymentMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table busi_game_payment
	 * @mbg.generated  Wed May 03 14:56:07 CST 2017
	 */
	long countByExample(BusiGamePaymentExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table busi_game_payment
	 * @mbg.generated  Wed May 03 14:56:07 CST 2017
	 */
	int deleteByExample(BusiGamePaymentExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table busi_game_payment
	 * @mbg.generated  Wed May 03 14:56:07 CST 2017
	 */
	int deleteByPrimaryKey(BusiGamePaymentKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table busi_game_payment
	 * @mbg.generated  Wed May 03 14:56:07 CST 2017
	 */
	int insert(BusiGamePayment record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table busi_game_payment
	 * @mbg.generated  Wed May 03 14:56:07 CST 2017
	 */
	int insertSelective(BusiGamePayment record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table busi_game_payment
	 * @mbg.generated  Wed May 03 14:56:07 CST 2017
	 */
	List<BusiGamePayment> selectByExample(BusiGamePaymentExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table busi_game_payment
	 * @mbg.generated  Wed May 03 14:56:07 CST 2017
	 */
	BusiGamePayment selectByPrimaryKey(BusiGamePaymentKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table busi_game_payment
	 * @mbg.generated  Wed May 03 14:56:07 CST 2017
	 */
	int updateByExampleSelective(@Param("record") BusiGamePayment record,
			@Param("example") BusiGamePaymentExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table busi_game_payment
	 * @mbg.generated  Wed May 03 14:56:07 CST 2017
	 */
	int updateByExample(@Param("record") BusiGamePayment record, @Param("example") BusiGamePaymentExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table busi_game_payment
	 * @mbg.generated  Wed May 03 14:56:07 CST 2017
	 */
	int updateByPrimaryKeySelective(BusiGamePayment record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table busi_game_payment
	 * @mbg.generated  Wed May 03 14:56:07 CST 2017
	 */
	int updateByPrimaryKey(BusiGamePayment record);
}