package game2peer.mybatis.dao;

import game2peer.mybatis.domain.BusiUserLogs;
import game2peer.mybatis.domain.BusiUserLogsExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface BusiUserLogsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table busi_user_logs
     *
     * @mbg.generated Mon May 15 08:36:44 CST 2017
     */
    long countByExample(BusiUserLogsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table busi_user_logs
     *
     * @mbg.generated Mon May 15 08:36:44 CST 2017
     */
    int deleteByExample(BusiUserLogsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table busi_user_logs
     *
     * @mbg.generated Mon May 15 08:36:44 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table busi_user_logs
     *
     * @mbg.generated Mon May 15 08:36:44 CST 2017
     */
    int insert(BusiUserLogs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table busi_user_logs
     *
     * @mbg.generated Mon May 15 08:36:44 CST 2017
     */
    int insertSelective(BusiUserLogs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table busi_user_logs
     *
     * @mbg.generated Mon May 15 08:36:44 CST 2017
     */
    List<BusiUserLogs> selectByExample(BusiUserLogsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table busi_user_logs
     *
     * @mbg.generated Mon May 15 08:36:44 CST 2017
     */
    BusiUserLogs selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table busi_user_logs
     *
     * @mbg.generated Mon May 15 08:36:44 CST 2017
     */
    int updateByExampleSelective(@Param("record") BusiUserLogs record, @Param("example") BusiUserLogsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table busi_user_logs
     *
     * @mbg.generated Mon May 15 08:36:44 CST 2017
     */
    int updateByExample(@Param("record") BusiUserLogs record, @Param("example") BusiUserLogsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table busi_user_logs
     *
     * @mbg.generated Mon May 15 08:36:44 CST 2017
     */
    int updateByPrimaryKeySelective(BusiUserLogs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table busi_user_logs
     *
     * @mbg.generated Mon May 15 08:36:44 CST 2017
     */
    int updateByPrimaryKey(BusiUserLogs record);
}