package game2peer.mybatis.dao;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import game2peer.mybatis.domain.BusiUserAccount;
import game2peer.mybatis.domain.BusiUserAccountExample;
import game2peer.mybatis.domain.BusiUserAccountKey;

@Mapper
public interface BusiUserAccountMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table busi_user_account
     *
     * @mbg.generated Thu May 18 20:46:39 CST 2017
     */
    long countByExample(BusiUserAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table busi_user_account
     *
     * @mbg.generated Thu May 18 20:46:39 CST 2017
     */
    int deleteByExample(BusiUserAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table busi_user_account
     *
     * @mbg.generated Thu May 18 20:46:39 CST 2017
     */
    int deleteByPrimaryKey(BusiUserAccountKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table busi_user_account
     *
     * @mbg.generated Thu May 18 20:46:39 CST 2017
     */
    int insert(BusiUserAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table busi_user_account
     *
     * @mbg.generated Thu May 18 20:46:39 CST 2017
     */
    int insertSelective(BusiUserAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table busi_user_account
     *
     * @mbg.generated Thu May 18 20:46:39 CST 2017
     */
    List<BusiUserAccount> selectByExample(BusiUserAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table busi_user_account
     *
     * @mbg.generated Thu May 18 20:46:39 CST 2017
     */
    BusiUserAccount selectByPrimaryKey(BusiUserAccountKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table busi_user_account
     *
     * @mbg.generated Thu May 18 20:46:39 CST 2017
     */
    int updateByExampleSelective(@Param("record") BusiUserAccount record, @Param("example") BusiUserAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table busi_user_account
     *
     * @mbg.generated Thu May 18 20:46:39 CST 2017
     */
    int updateByExample(@Param("record") BusiUserAccount record, @Param("example") BusiUserAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table busi_user_account
     *
     * @mbg.generated Thu May 18 20:46:39 CST 2017
     */
    int updateByPrimaryKeySelective(BusiUserAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table busi_user_account
     *
     * @mbg.generated Thu May 18 20:46:39 CST 2017
     */
    int updateByPrimaryKey(BusiUserAccount record);
}