package game2peer.mybatis.dao;

import game2peer.mybatis.domain.BusiUserGallery;
import game2peer.mybatis.domain.BusiUserGalleryExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface BusiUserGalleryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table busi_user_gallery
     *
     * @mbg.generated Mon May 15 08:36:44 CST 2017
     */
    long countByExample(BusiUserGalleryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table busi_user_gallery
     *
     * @mbg.generated Mon May 15 08:36:44 CST 2017
     */
    int deleteByExample(BusiUserGalleryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table busi_user_gallery
     *
     * @mbg.generated Mon May 15 08:36:44 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table busi_user_gallery
     *
     * @mbg.generated Mon May 15 08:36:44 CST 2017
     */
    int insert(BusiUserGallery record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table busi_user_gallery
     *
     * @mbg.generated Mon May 15 08:36:44 CST 2017
     */
    int insertSelective(BusiUserGallery record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table busi_user_gallery
     *
     * @mbg.generated Mon May 15 08:36:44 CST 2017
     */
    List<BusiUserGallery> selectByExample(BusiUserGalleryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table busi_user_gallery
     *
     * @mbg.generated Mon May 15 08:36:44 CST 2017
     */
    BusiUserGallery selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table busi_user_gallery
     *
     * @mbg.generated Mon May 15 08:36:44 CST 2017
     */
    int updateByExampleSelective(@Param("record") BusiUserGallery record, @Param("example") BusiUserGalleryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table busi_user_gallery
     *
     * @mbg.generated Mon May 15 08:36:44 CST 2017
     */
    int updateByExample(@Param("record") BusiUserGallery record, @Param("example") BusiUserGalleryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table busi_user_gallery
     *
     * @mbg.generated Mon May 15 08:36:44 CST 2017
     */
    int updateByPrimaryKeySelective(BusiUserGallery record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table busi_user_gallery
     *
     * @mbg.generated Mon May 15 08:36:44 CST 2017
     */
    int updateByPrimaryKey(BusiUserGallery record);
}