package game2peer.mybatis.dao;

import game2peer.mybatis.domain.BusiUserLike;
import game2peer.mybatis.domain.BusiUserLikeExample;
import game2peer.mybatis.domain.BusiUserLikeKey;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface BusiUserLikeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table busi_user_like
     *
     * @mbg.generated Fri May 19 21:57:37 CST 2017
     */
    long countByExample(BusiUserLikeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table busi_user_like
     *
     * @mbg.generated Fri May 19 21:57:37 CST 2017
     */
    int deleteByExample(BusiUserLikeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table busi_user_like
     *
     * @mbg.generated Fri May 19 21:57:37 CST 2017
     */
    int deleteByPrimaryKey(BusiUserLikeKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table busi_user_like
     *
     * @mbg.generated Fri May 19 21:57:37 CST 2017
     */
    int insert(BusiUserLike record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table busi_user_like
     *
     * @mbg.generated Fri May 19 21:57:37 CST 2017
     */
    int insertSelective(BusiUserLike record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table busi_user_like
     *
     * @mbg.generated Fri May 19 21:57:37 CST 2017
     */
    List<BusiUserLike> selectByExample(BusiUserLikeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table busi_user_like
     *
     * @mbg.generated Fri May 19 21:57:37 CST 2017
     */
    BusiUserLike selectByPrimaryKey(BusiUserLikeKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table busi_user_like
     *
     * @mbg.generated Fri May 19 21:57:37 CST 2017
     */
    int updateByExampleSelective(@Param("record") BusiUserLike record, @Param("example") BusiUserLikeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table busi_user_like
     *
     * @mbg.generated Fri May 19 21:57:37 CST 2017
     */
    int updateByExample(@Param("record") BusiUserLike record, @Param("example") BusiUserLikeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table busi_user_like
     *
     * @mbg.generated Fri May 19 21:57:37 CST 2017
     */
    int updateByPrimaryKeySelective(BusiUserLike record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table busi_user_like
     *
     * @mbg.generated Fri May 19 21:57:37 CST 2017
     */
    int updateByPrimaryKey(BusiUserLike record);
}