package game2peer.mybatis.dao;

import game2peer.mybatis.domain.BusiGameProfits;
import game2peer.mybatis.domain.BusiGameProfitsExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface BusiGameProfitsMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table busi_game_profits
	 * @mbg.generated  Wed May 10 12:03:08 CST 2017
	 */
	long countByExample(BusiGameProfitsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table busi_game_profits
	 * @mbg.generated  Wed May 10 12:03:08 CST 2017
	 */
	int deleteByExample(BusiGameProfitsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table busi_game_profits
	 * @mbg.generated  Wed May 10 12:03:08 CST 2017
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table busi_game_profits
	 * @mbg.generated  Wed May 10 12:03:08 CST 2017
	 */
	int insert(BusiGameProfits record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table busi_game_profits
	 * @mbg.generated  Wed May 10 12:03:08 CST 2017
	 */
	int insertSelective(BusiGameProfits record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table busi_game_profits
	 * @mbg.generated  Wed May 10 12:03:08 CST 2017
	 */
	List<BusiGameProfits> selectByExample(BusiGameProfitsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table busi_game_profits
	 * @mbg.generated  Wed May 10 12:03:08 CST 2017
	 */
	BusiGameProfits selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table busi_game_profits
	 * @mbg.generated  Wed May 10 12:03:08 CST 2017
	 */
	int updateByExampleSelective(@Param("record") BusiGameProfits record,
			@Param("example") BusiGameProfitsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table busi_game_profits
	 * @mbg.generated  Wed May 10 12:03:08 CST 2017
	 */
	int updateByExample(@Param("record") BusiGameProfits record, @Param("example") BusiGameProfitsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table busi_game_profits
	 * @mbg.generated  Wed May 10 12:03:08 CST 2017
	 */
	int updateByPrimaryKeySelective(BusiGameProfits record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table busi_game_profits
	 * @mbg.generated  Wed May 10 12:03:08 CST 2017
	 */
	int updateByPrimaryKey(BusiGameProfits record);
}