package game2peer.mybatis.dao;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import game2peer.mybatis.domain.BusiExchange;
import game2peer.mybatis.domain.BusiExchangeExample;

@Mapper
public interface BusiExchangeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table busi_exchange
     *
     * @mbg.generated Fri May 19 09:10:27 CST 2017
     */
    long countByExample(BusiExchangeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table busi_exchange
     *
     * @mbg.generated Fri May 19 09:10:27 CST 2017
     */
    int deleteByExample(BusiExchangeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table busi_exchange
     *
     * @mbg.generated Fri May 19 09:10:27 CST 2017
     */
    int deleteByPrimaryKey(String currency);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table busi_exchange
     *
     * @mbg.generated Fri May 19 09:10:27 CST 2017
     */
    int insert(BusiExchange record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table busi_exchange
     *
     * @mbg.generated Fri May 19 09:10:27 CST 2017
     */
    int insertSelective(BusiExchange record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table busi_exchange
     *
     * @mbg.generated Fri May 19 09:10:27 CST 2017
     */
    List<BusiExchange> selectByExample(BusiExchangeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table busi_exchange
     *
     * @mbg.generated Fri May 19 09:10:27 CST 2017
     */
    BusiExchange selectByPrimaryKey(String currency);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table busi_exchange
     *
     * @mbg.generated Fri May 19 09:10:27 CST 2017
     */
    int updateByExampleSelective(@Param("record") BusiExchange record, @Param("example") BusiExchangeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table busi_exchange
     *
     * @mbg.generated Fri May 19 09:10:27 CST 2017
     */
    int updateByExample(@Param("record") BusiExchange record, @Param("example") BusiExchangeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table busi_exchange
     *
     * @mbg.generated Fri May 19 09:10:27 CST 2017
     */
    int updateByPrimaryKeySelective(BusiExchange record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table busi_exchange
     *
     * @mbg.generated Fri May 19 09:10:27 CST 2017
     */
    int updateByPrimaryKey(BusiExchange record);
}