package game2peer.mybatis.dao;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import game2peer.mybatis.domain.GroupUrl;
import game2peer.mybatis.domain.GroupUrlExample;

@Mapper
public interface GroupUrlMapper {
	
	List<GroupUrl> getAccessRightByGroup(@Param("id") String id);
	
	List<GroupUrl> getAll();
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_url
     *
     * @mbg.generated Thu Mar 30 08:58:31 CST 2017
     */
    long countByExample(GroupUrlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_url
     *
     * @mbg.generated Thu Mar 30 08:58:31 CST 2017
     */
    int deleteByExample(GroupUrlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_url
     *
     * @mbg.generated Thu Mar 30 08:58:31 CST 2017
     */
    int insert(GroupUrl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_url
     *
     * @mbg.generated Thu Mar 30 08:58:31 CST 2017
     */
    int insertSelective(GroupUrl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_url
     *
     * @mbg.generated Thu Mar 30 08:58:31 CST 2017
     */
    List<GroupUrl> selectByExample(GroupUrlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_url
     *
     * @mbg.generated Thu Mar 30 08:58:31 CST 2017
     */
    int updateByExampleSelective(@Param("record") GroupUrl record, @Param("example") GroupUrlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_url
     *
     * @mbg.generated Thu Mar 30 08:58:31 CST 2017
     */
    int updateByExample(@Param("record") GroupUrl record, @Param("example") GroupUrlExample example);
}