package game2peer.mybatis.dao;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import game2peer.mybatis.domain.GroupRoleExample;
import game2peer.mybatis.domain.GroupRoleKey;

@Mapper
public interface GroupRoleMapper {
	
	List<GroupRoleKey> getRoleIds(@Param("groupId") Integer id);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_role
     *
     * @mbg.generated Tue Mar 28 12:27:59 CST 2017
     */
    long countByExample(GroupRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_role
     *
     * @mbg.generated Tue Mar 28 12:27:59 CST 2017
     */
    int deleteByExample(GroupRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_role
     *
     * @mbg.generated Tue Mar 28 12:27:59 CST 2017
     */
    int deleteByPrimaryKey(GroupRoleKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_role
     *
     * @mbg.generated Tue Mar 28 12:27:59 CST 2017
     */
    int insert(GroupRoleKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_role
     *
     * @mbg.generated Tue Mar 28 12:27:59 CST 2017
     */
    int insertSelective(GroupRoleKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_role
     *
     * @mbg.generated Tue Mar 28 12:27:59 CST 2017
     */
    List<GroupRoleKey> selectByExample(GroupRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_role
     *
     * @mbg.generated Tue Mar 28 12:27:59 CST 2017
     */
    int updateByExampleSelective(@Param("record") GroupRoleKey record, @Param("example") GroupRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_role
     *
     * @mbg.generated Tue Mar 28 12:27:59 CST 2017
     */
    int updateByExample(@Param("record") GroupRoleKey record, @Param("example") GroupRoleExample example);
}