package game2peer.mybatis.dao;

import game2peer.mybatis.domain.NavigationGroup;
import game2peer.mybatis.domain.NavigationGroupExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface NavigationGroupMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table navigation_group
     *
     * @mbg.generated Mon May 15 08:36:44 CST 2017
     */
    long countByExample(NavigationGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table navigation_group
     *
     * @mbg.generated Mon May 15 08:36:44 CST 2017
     */
    int deleteByExample(NavigationGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table navigation_group
     *
     * @mbg.generated Mon May 15 08:36:44 CST 2017
     */
    int deleteByPrimaryKey(Integer groupId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table navigation_group
     *
     * @mbg.generated Mon May 15 08:36:44 CST 2017
     */
    int insert(NavigationGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table navigation_group
     *
     * @mbg.generated Mon May 15 08:36:44 CST 2017
     */
    int insertSelective(NavigationGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table navigation_group
     *
     * @mbg.generated Mon May 15 08:36:44 CST 2017
     */
    List<NavigationGroup> selectByExample(NavigationGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table navigation_group
     *
     * @mbg.generated Mon May 15 08:36:44 CST 2017
     */
    NavigationGroup selectByPrimaryKey(Integer groupId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table navigation_group
     *
     * @mbg.generated Mon May 15 08:36:44 CST 2017
     */
    int updateByExampleSelective(@Param("record") NavigationGroup record, @Param("example") NavigationGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table navigation_group
     *
     * @mbg.generated Mon May 15 08:36:44 CST 2017
     */
    int updateByExample(@Param("record") NavigationGroup record, @Param("example") NavigationGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table navigation_group
     *
     * @mbg.generated Mon May 15 08:36:44 CST 2017
     */
    int updateByPrimaryKeySelective(NavigationGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table navigation_group
     *
     * @mbg.generated Mon May 15 08:36:44 CST 2017
     */
    int updateByPrimaryKey(NavigationGroup record);
}