package game2peer.mybatis.dao;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import game2peer.mybatis.domain.Nav;
import game2peer.mybatis.domain.NavExample;

@Mapper
public interface NavMapper {

	List<Nav> selectByParentId(@Param("id") Integer id);
	
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table nav
	 * @mbg.generated  Thu Apr 13 08:28:07 CST 2017
	 */
	long countByExample(NavExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table nav
	 * @mbg.generated  Thu Apr 13 08:28:07 CST 2017
	 */
	int deleteByExample(NavExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table nav
	 * @mbg.generated  Thu Apr 13 08:28:07 CST 2017
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table nav
	 * @mbg.generated  Thu Apr 13 08:28:07 CST 2017
	 */
	int insert(Nav record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table nav
	 * @mbg.generated  Thu Apr 13 08:28:07 CST 2017
	 */
	int insertSelective(Nav record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table nav
	 * @mbg.generated  Thu Apr 13 08:28:07 CST 2017
	 */
	List<Nav> selectByExample(NavExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table nav
	 * @mbg.generated  Thu Apr 13 08:28:07 CST 2017
	 */
	Nav selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table nav
	 * @mbg.generated  Thu Apr 13 08:28:07 CST 2017
	 */
	int updateByExampleSelective(@Param("record") Nav record, @Param("example") NavExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table nav
	 * @mbg.generated  Thu Apr 13 08:28:07 CST 2017
	 */
	int updateByExample(@Param("record") Nav record, @Param("example") NavExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table nav
	 * @mbg.generated  Thu Apr 13 08:28:07 CST 2017
	 */
	int updateByPrimaryKeySelective(Nav record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table nav
	 * @mbg.generated  Thu Apr 13 08:28:07 CST 2017
	 */
	int updateByPrimaryKey(Nav record);
}