package game2peer.mybatis.dao;

import game2peer.mybatis.domain.Pages;
import game2peer.mybatis.domain.PagesExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;


@Mapper
public interface PagesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pages
     *
     * @mbg.generated Mon May 15 08:36:44 CST 2017
     */
    long countByExample(PagesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pages
     *
     * @mbg.generated Mon May 15 08:36:44 CST 2017
     */
    int deleteByExample(PagesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pages
     *
     * @mbg.generated Mon May 15 08:36:44 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pages
     *
     * @mbg.generated Mon May 15 08:36:44 CST 2017
     */
    int insert(Pages record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pages
     *
     * @mbg.generated Mon May 15 08:36:44 CST 2017
     */
    int insertSelective(Pages record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pages
     *
     * @mbg.generated Mon May 15 08:36:44 CST 2017
     */
    List<Pages> selectByExample(PagesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pages
     *
     * @mbg.generated Mon May 15 08:36:44 CST 2017
     */
    Pages selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pages
     *
     * @mbg.generated Mon May 15 08:36:44 CST 2017
     */
    int updateByExampleSelective(@Param("record") Pages record, @Param("example") PagesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pages
     *
     * @mbg.generated Mon May 15 08:36:44 CST 2017
     */
    int updateByExample(@Param("record") Pages record, @Param("example") PagesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pages
     *
     * @mbg.generated Mon May 15 08:36:44 CST 2017
     */
    int updateByPrimaryKeySelective(Pages record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pages
     *
     * @mbg.generated Mon May 15 08:36:44 CST 2017
     */
    int updateByPrimaryKey(Pages record);
}