package game2peer.mybatis.dao;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import game2peer.mybatis.domain.Pages;
import game2peer.mybatis.domain.PagesExample;

@Mapper
public interface PagesMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pages
	 * @mbg.generated  Wed May 10 12:03:08 CST 2017
	 */
	long countByExample(PagesExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pages
	 * @mbg.generated  Wed May 10 12:03:08 CST 2017
	 */
	int deleteByExample(PagesExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pages
	 * @mbg.generated  Wed May 10 12:03:08 CST 2017
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pages
	 * @mbg.generated  Wed May 10 12:03:08 CST 2017
	 */
	int insert(Pages record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pages
	 * @mbg.generated  Wed May 10 12:03:08 CST 2017
	 */
	int insertSelective(Pages record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pages
	 * @mbg.generated  Wed May 10 12:03:08 CST 2017
	 */
	List<Pages> selectByExample(PagesExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pages
	 * @mbg.generated  Wed May 10 12:03:08 CST 2017
	 */
	Pages selectByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pages
	 * @mbg.generated  Wed May 10 12:03:08 CST 2017
	 */
	int updateByExampleSelective(@Param("record") Pages record, @Param("example") PagesExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pages
	 * @mbg.generated  Wed May 10 12:03:08 CST 2017
	 */
	int updateByExample(@Param("record") Pages record, @Param("example") PagesExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pages
	 * @mbg.generated  Wed May 10 12:03:08 CST 2017
	 */
	int updateByPrimaryKeySelective(Pages record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pages
	 * @mbg.generated  Wed May 10 12:03:08 CST 2017
	 */
	int updateByPrimaryKey(Pages record);
}