package game2peer.mybatis.dao;

import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import game2peer.mybatis.domain.RestApis;
import game2peer.mybatis.domain.RestApisExample;

@Mapper
public interface RestApisMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rest_apis
     *
     * @mbg.generated Mon May 08 11:10:07 CST 2017
     */
    long countByExample(RestApisExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rest_apis
     *
     * @mbg.generated Mon May 08 11:10:07 CST 2017
     */
    int deleteByExample(RestApisExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rest_apis
     *
     * @mbg.generated Mon May 08 11:10:07 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rest_apis
     *
     * @mbg.generated Mon May 08 11:10:07 CST 2017
     */
    int insert(RestApis record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rest_apis
     *
     * @mbg.generated Mon May 08 11:10:07 CST 2017
     */
    int insertSelective(RestApis record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rest_apis
     *
     * @mbg.generated Mon May 08 11:10:07 CST 2017
     */
    List<RestApis> selectByExample(RestApisExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rest_apis
     *
     * @mbg.generated Mon May 08 11:10:07 CST 2017
     */
    RestApis selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rest_apis
     *
     * @mbg.generated Mon May 08 11:10:07 CST 2017
     */
    int updateByExampleSelective(@Param("record") RestApis record, @Param("example") RestApisExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rest_apis
     *
     * @mbg.generated Mon May 08 11:10:07 CST 2017
     */
    int updateByExample(@Param("record") RestApis record, @Param("example") RestApisExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rest_apis
     *
     * @mbg.generated Mon May 08 11:10:07 CST 2017
     */
    int updateByPrimaryKeySelective(RestApis record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rest_apis
     *
     * @mbg.generated Mon May 08 11:10:07 CST 2017
     */
    int updateByPrimaryKey(RestApis record);
}