package game2peer.mybatis.dao;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import game2peer.mybatis.domain.UserMail;
import game2peer.mybatis.domain.UserMailExample;

@Mapper
public interface UserMailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_mail
     *
     * @mbg.generated Fri May 19 21:57:37 CST 2017
     */
    long countByExample(UserMailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_mail
     *
     * @mbg.generated Fri May 19 21:57:37 CST 2017
     */
    int deleteByExample(UserMailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_mail
     *
     * @mbg.generated Fri May 19 21:57:37 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_mail
     *
     * @mbg.generated Fri May 19 21:57:37 CST 2017
     */
    int insert(UserMail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_mail
     *
     * @mbg.generated Fri May 19 21:57:37 CST 2017
     */
    int insertSelective(UserMail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_mail
     *
     * @mbg.generated Fri May 19 21:57:37 CST 2017
     */
    List<UserMail> selectByExampleWithBLOBs(UserMailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_mail
     *
     * @mbg.generated Fri May 19 21:57:37 CST 2017
     */
    List<UserMail> selectByExample(UserMailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_mail
     *
     * @mbg.generated Fri May 19 21:57:37 CST 2017
     */
    UserMail selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_mail
     *
     * @mbg.generated Fri May 19 21:57:37 CST 2017
     */
    int updateByExampleSelective(@Param("record") UserMail record, @Param("example") UserMailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_mail
     *
     * @mbg.generated Fri May 19 21:57:37 CST 2017
     */
    int updateByExampleWithBLOBs(@Param("record") UserMail record, @Param("example") UserMailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_mail
     *
     * @mbg.generated Fri May 19 21:57:37 CST 2017
     */
    int updateByExample(@Param("record") UserMail record, @Param("example") UserMailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_mail
     *
     * @mbg.generated Fri May 19 21:57:37 CST 2017
     */
    int updateByPrimaryKeySelective(UserMail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_mail
     *
     * @mbg.generated Fri May 19 21:57:37 CST 2017
     */
    int updateByPrimaryKeyWithBLOBs(UserMail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_mail
     *
     * @mbg.generated Fri May 19 21:57:37 CST 2017
     */
    int updateByPrimaryKey(UserMail record);
}