package game2peer.mybatis.domain;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class BusiGameUserExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table busi_game_user
     *
     * @mbg.generated Mon May 22 18:10:09 CST 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table busi_game_user
     *
     * @mbg.generated Mon May 22 18:10:09 CST 2017
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table busi_game_user
     *
     * @mbg.generated Mon May 22 18:10:09 CST 2017
     */
    protected List<Criteria> oredCriteria;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table busi_game_user
     *
     * @mbg.generated Mon May 22 18:10:09 CST 2017
     */
    protected int limitStart = -1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table busi_game_user
     *
     * @mbg.generated Mon May 22 18:10:09 CST 2017
     */
    protected int limitEnd = -1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table busi_game_user
     *
     * @mbg.generated Mon May 22 18:10:09 CST 2017
     */
    protected String groupBy = null;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table busi_game_user
     *
     * @mbg.generated Mon May 22 18:10:09 CST 2017
     */
    public BusiGameUserExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table busi_game_user
     *
     * @mbg.generated Mon May 22 18:10:09 CST 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table busi_game_user
     *
     * @mbg.generated Mon May 22 18:10:09 CST 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table busi_game_user
     *
     * @mbg.generated Mon May 22 18:10:09 CST 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table busi_game_user
     *
     * @mbg.generated Mon May 22 18:10:09 CST 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table busi_game_user
     *
     * @mbg.generated Mon May 22 18:10:09 CST 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table busi_game_user
     *
     * @mbg.generated Mon May 22 18:10:09 CST 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table busi_game_user
     *
     * @mbg.generated Mon May 22 18:10:09 CST 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table busi_game_user
     *
     * @mbg.generated Mon May 22 18:10:09 CST 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table busi_game_user
     *
     * @mbg.generated Mon May 22 18:10:09 CST 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table busi_game_user
     *
     * @mbg.generated Mon May 22 18:10:09 CST 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table busi_game_user
     *
     * @mbg.generated Mon May 22 18:10:09 CST 2017
     */
    public void setLimitStart(int limitStart) {
        this.limitStart=limitStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table busi_game_user
     *
     * @mbg.generated Mon May 22 18:10:09 CST 2017
     */
    public int getLimitStart() {
        return limitStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table busi_game_user
     *
     * @mbg.generated Mon May 22 18:10:09 CST 2017
     */
    public void setLimitEnd(int limitEnd) {
        this.limitEnd=limitEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table busi_game_user
     *
     * @mbg.generated Mon May 22 18:10:09 CST 2017
     */
    public int getLimitEnd() {
        return limitEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table busi_game_user
     *
     * @mbg.generated Mon May 22 18:10:09 CST 2017
     */
    public void setGroupBy(String groupBy) {
        this.groupBy=groupBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table busi_game_user
     *
     * @mbg.generated Mon May 22 18:10:09 CST 2017
     */
    public String getGroupBy() {
        return groupBy;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table busi_game_user
     *
     * @mbg.generated Mon May 22 18:10:09 CST 2017
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andGameCodeIsNull() {
            addCriterion("game_code is null");
            return (Criteria) this;
        }

        public Criteria andGameCodeIsNotNull() {
            addCriterion("game_code is not null");
            return (Criteria) this;
        }

        public Criteria andGameCodeEqualTo(String value) {
            addCriterion("game_code =", value, "gameCode");
            return (Criteria) this;
        }

        public Criteria andGameCodeNotEqualTo(String value) {
            addCriterion("game_code <>", value, "gameCode");
            return (Criteria) this;
        }

        public Criteria andGameCodeGreaterThan(String value) {
            addCriterion("game_code >", value, "gameCode");
            return (Criteria) this;
        }

        public Criteria andGameCodeGreaterThanOrEqualTo(String value) {
            addCriterion("game_code >=", value, "gameCode");
            return (Criteria) this;
        }

        public Criteria andGameCodeLessThan(String value) {
            addCriterion("game_code <", value, "gameCode");
            return (Criteria) this;
        }

        public Criteria andGameCodeLessThanOrEqualTo(String value) {
            addCriterion("game_code <=", value, "gameCode");
            return (Criteria) this;
        }

        public Criteria andGameCodeLike(String value) {
            addCriterion("game_code like", value, "gameCode");
            return (Criteria) this;
        }

        public Criteria andGameCodeNotLike(String value) {
            addCriterion("game_code not like", value, "gameCode");
            return (Criteria) this;
        }

        public Criteria andGameCodeIn(List<String> values) {
            addCriterion("game_code in", values, "gameCode");
            return (Criteria) this;
        }

        public Criteria andGameCodeNotIn(List<String> values) {
            addCriterion("game_code not in", values, "gameCode");
            return (Criteria) this;
        }

        public Criteria andGameCodeBetween(String value1, String value2) {
            addCriterion("game_code between", value1, value2, "gameCode");
            return (Criteria) this;
        }

        public Criteria andGameCodeNotBetween(String value1, String value2) {
            addCriterion("game_code not between", value1, value2, "gameCode");
            return (Criteria) this;
        }

        public Criteria andLoginNameIsNull() {
            addCriterion("login_name is null");
            return (Criteria) this;
        }

        public Criteria andLoginNameIsNotNull() {
            addCriterion("login_name is not null");
            return (Criteria) this;
        }

        public Criteria andLoginNameEqualTo(String value) {
            addCriterion("login_name =", value, "loginName");
            return (Criteria) this;
        }

        public Criteria andLoginNameNotEqualTo(String value) {
            addCriterion("login_name <>", value, "loginName");
            return (Criteria) this;
        }

        public Criteria andLoginNameGreaterThan(String value) {
            addCriterion("login_name >", value, "loginName");
            return (Criteria) this;
        }

        public Criteria andLoginNameGreaterThanOrEqualTo(String value) {
            addCriterion("login_name >=", value, "loginName");
            return (Criteria) this;
        }

        public Criteria andLoginNameLessThan(String value) {
            addCriterion("login_name <", value, "loginName");
            return (Criteria) this;
        }

        public Criteria andLoginNameLessThanOrEqualTo(String value) {
            addCriterion("login_name <=", value, "loginName");
            return (Criteria) this;
        }

        public Criteria andLoginNameLike(String value) {
            addCriterion("login_name like", value, "loginName");
            return (Criteria) this;
        }

        public Criteria andLoginNameNotLike(String value) {
            addCriterion("login_name not like", value, "loginName");
            return (Criteria) this;
        }

        public Criteria andLoginNameIn(List<String> values) {
            addCriterion("login_name in", values, "loginName");
            return (Criteria) this;
        }

        public Criteria andLoginNameNotIn(List<String> values) {
            addCriterion("login_name not in", values, "loginName");
            return (Criteria) this;
        }

        public Criteria andLoginNameBetween(String value1, String value2) {
            addCriterion("login_name between", value1, value2, "loginName");
            return (Criteria) this;
        }

        public Criteria andLoginNameNotBetween(String value1, String value2) {
            addCriterion("login_name not between", value1, value2, "loginName");
            return (Criteria) this;
        }

        public Criteria andGameUserIdIsNull() {
            addCriterion("game_user_id is null");
            return (Criteria) this;
        }

        public Criteria andGameUserIdIsNotNull() {
            addCriterion("game_user_id is not null");
            return (Criteria) this;
        }

        public Criteria andGameUserIdEqualTo(String value) {
            addCriterion("game_user_id =", value, "gameUserId");
            return (Criteria) this;
        }

        public Criteria andGameUserIdNotEqualTo(String value) {
            addCriterion("game_user_id <>", value, "gameUserId");
            return (Criteria) this;
        }

        public Criteria andGameUserIdGreaterThan(String value) {
            addCriterion("game_user_id >", value, "gameUserId");
            return (Criteria) this;
        }

        public Criteria andGameUserIdGreaterThanOrEqualTo(String value) {
            addCriterion("game_user_id >=", value, "gameUserId");
            return (Criteria) this;
        }

        public Criteria andGameUserIdLessThan(String value) {
            addCriterion("game_user_id <", value, "gameUserId");
            return (Criteria) this;
        }

        public Criteria andGameUserIdLessThanOrEqualTo(String value) {
            addCriterion("game_user_id <=", value, "gameUserId");
            return (Criteria) this;
        }

        public Criteria andGameUserIdLike(String value) {
            addCriterion("game_user_id like", value, "gameUserId");
            return (Criteria) this;
        }

        public Criteria andGameUserIdNotLike(String value) {
            addCriterion("game_user_id not like", value, "gameUserId");
            return (Criteria) this;
        }

        public Criteria andGameUserIdIn(List<String> values) {
            addCriterion("game_user_id in", values, "gameUserId");
            return (Criteria) this;
        }

        public Criteria andGameUserIdNotIn(List<String> values) {
            addCriterion("game_user_id not in", values, "gameUserId");
            return (Criteria) this;
        }

        public Criteria andGameUserIdBetween(String value1, String value2) {
            addCriterion("game_user_id between", value1, value2, "gameUserId");
            return (Criteria) this;
        }

        public Criteria andGameUserIdNotBetween(String value1, String value2) {
            addCriterion("game_user_id not between", value1, value2, "gameUserId");
            return (Criteria) this;
        }

        public Criteria andNiceNameIsNull() {
            addCriterion("nice_name is null");
            return (Criteria) this;
        }

        public Criteria andNiceNameIsNotNull() {
            addCriterion("nice_name is not null");
            return (Criteria) this;
        }

        public Criteria andNiceNameEqualTo(String value) {
            addCriterion("nice_name =", value, "niceName");
            return (Criteria) this;
        }

        public Criteria andNiceNameNotEqualTo(String value) {
            addCriterion("nice_name <>", value, "niceName");
            return (Criteria) this;
        }

        public Criteria andNiceNameGreaterThan(String value) {
            addCriterion("nice_name >", value, "niceName");
            return (Criteria) this;
        }

        public Criteria andNiceNameGreaterThanOrEqualTo(String value) {
            addCriterion("nice_name >=", value, "niceName");
            return (Criteria) this;
        }

        public Criteria andNiceNameLessThan(String value) {
            addCriterion("nice_name <", value, "niceName");
            return (Criteria) this;
        }

        public Criteria andNiceNameLessThanOrEqualTo(String value) {
            addCriterion("nice_name <=", value, "niceName");
            return (Criteria) this;
        }

        public Criteria andNiceNameLike(String value) {
            addCriterion("nice_name like", value, "niceName");
            return (Criteria) this;
        }

        public Criteria andNiceNameNotLike(String value) {
            addCriterion("nice_name not like", value, "niceName");
            return (Criteria) this;
        }

        public Criteria andNiceNameIn(List<String> values) {
            addCriterion("nice_name in", values, "niceName");
            return (Criteria) this;
        }

        public Criteria andNiceNameNotIn(List<String> values) {
            addCriterion("nice_name not in", values, "niceName");
            return (Criteria) this;
        }

        public Criteria andNiceNameBetween(String value1, String value2) {
            addCriterion("nice_name between", value1, value2, "niceName");
            return (Criteria) this;
        }

        public Criteria andNiceNameNotBetween(String value1, String value2) {
            addCriterion("nice_name not between", value1, value2, "niceName");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andPasswordIsNull() {
            addCriterion("password is null");
            return (Criteria) this;
        }

        public Criteria andPasswordIsNotNull() {
            addCriterion("password is not null");
            return (Criteria) this;
        }

        public Criteria andPasswordEqualTo(String value) {
            addCriterion("password =", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordNotEqualTo(String value) {
            addCriterion("password <>", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordGreaterThan(String value) {
            addCriterion("password >", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordGreaterThanOrEqualTo(String value) {
            addCriterion("password >=", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordLessThan(String value) {
            addCriterion("password <", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordLessThanOrEqualTo(String value) {
            addCriterion("password <=", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordLike(String value) {
            addCriterion("password like", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordNotLike(String value) {
            addCriterion("password not like", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordIn(List<String> values) {
            addCriterion("password in", values, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordNotIn(List<String> values) {
            addCriterion("password not in", values, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordBetween(String value1, String value2) {
            addCriterion("password between", value1, value2, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordNotBetween(String value1, String value2) {
            addCriterion("password not between", value1, value2, "password");
            return (Criteria) this;
        }

        public Criteria andVeryifyCodeIsNull() {
            addCriterion("veryify_code is null");
            return (Criteria) this;
        }

        public Criteria andVeryifyCodeIsNotNull() {
            addCriterion("veryify_code is not null");
            return (Criteria) this;
        }

        public Criteria andVeryifyCodeEqualTo(String value) {
            addCriterion("veryify_code =", value, "veryifyCode");
            return (Criteria) this;
        }

        public Criteria andVeryifyCodeNotEqualTo(String value) {
            addCriterion("veryify_code <>", value, "veryifyCode");
            return (Criteria) this;
        }

        public Criteria andVeryifyCodeGreaterThan(String value) {
            addCriterion("veryify_code >", value, "veryifyCode");
            return (Criteria) this;
        }

        public Criteria andVeryifyCodeGreaterThanOrEqualTo(String value) {
            addCriterion("veryify_code >=", value, "veryifyCode");
            return (Criteria) this;
        }

        public Criteria andVeryifyCodeLessThan(String value) {
            addCriterion("veryify_code <", value, "veryifyCode");
            return (Criteria) this;
        }

        public Criteria andVeryifyCodeLessThanOrEqualTo(String value) {
            addCriterion("veryify_code <=", value, "veryifyCode");
            return (Criteria) this;
        }

        public Criteria andVeryifyCodeLike(String value) {
            addCriterion("veryify_code like", value, "veryifyCode");
            return (Criteria) this;
        }

        public Criteria andVeryifyCodeNotLike(String value) {
            addCriterion("veryify_code not like", value, "veryifyCode");
            return (Criteria) this;
        }

        public Criteria andVeryifyCodeIn(List<String> values) {
            addCriterion("veryify_code in", values, "veryifyCode");
            return (Criteria) this;
        }

        public Criteria andVeryifyCodeNotIn(List<String> values) {
            addCriterion("veryify_code not in", values, "veryifyCode");
            return (Criteria) this;
        }

        public Criteria andVeryifyCodeBetween(String value1, String value2) {
            addCriterion("veryify_code between", value1, value2, "veryifyCode");
            return (Criteria) this;
        }

        public Criteria andVeryifyCodeNotBetween(String value1, String value2) {
            addCriterion("veryify_code not between", value1, value2, "veryifyCode");
            return (Criteria) this;
        }

        public Criteria andVerifyOkIsNull() {
            addCriterion("verify_ok is null");
            return (Criteria) this;
        }

        public Criteria andVerifyOkIsNotNull() {
            addCriterion("verify_ok is not null");
            return (Criteria) this;
        }

        public Criteria andVerifyOkEqualTo(Integer value) {
            addCriterion("verify_ok =", value, "verifyOk");
            return (Criteria) this;
        }

        public Criteria andVerifyOkNotEqualTo(Integer value) {
            addCriterion("verify_ok <>", value, "verifyOk");
            return (Criteria) this;
        }

        public Criteria andVerifyOkGreaterThan(Integer value) {
            addCriterion("verify_ok >", value, "verifyOk");
            return (Criteria) this;
        }

        public Criteria andVerifyOkGreaterThanOrEqualTo(Integer value) {
            addCriterion("verify_ok >=", value, "verifyOk");
            return (Criteria) this;
        }

        public Criteria andVerifyOkLessThan(Integer value) {
            addCriterion("verify_ok <", value, "verifyOk");
            return (Criteria) this;
        }

        public Criteria andVerifyOkLessThanOrEqualTo(Integer value) {
            addCriterion("verify_ok <=", value, "verifyOk");
            return (Criteria) this;
        }

        public Criteria andVerifyOkIn(List<Integer> values) {
            addCriterion("verify_ok in", values, "verifyOk");
            return (Criteria) this;
        }

        public Criteria andVerifyOkNotIn(List<Integer> values) {
            addCriterion("verify_ok not in", values, "verifyOk");
            return (Criteria) this;
        }

        public Criteria andVerifyOkBetween(Integer value1, Integer value2) {
            addCriterion("verify_ok between", value1, value2, "verifyOk");
            return (Criteria) this;
        }

        public Criteria andVerifyOkNotBetween(Integer value1, Integer value2) {
            addCriterion("verify_ok not between", value1, value2, "verifyOk");
            return (Criteria) this;
        }

        public Criteria andEmailIsNull() {
            addCriterion("email is null");
            return (Criteria) this;
        }

        public Criteria andEmailIsNotNull() {
            addCriterion("email is not null");
            return (Criteria) this;
        }

        public Criteria andEmailEqualTo(String value) {
            addCriterion("email =", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailNotEqualTo(String value) {
            addCriterion("email <>", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailGreaterThan(String value) {
            addCriterion("email >", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailGreaterThanOrEqualTo(String value) {
            addCriterion("email >=", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailLessThan(String value) {
            addCriterion("email <", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailLessThanOrEqualTo(String value) {
            addCriterion("email <=", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailLike(String value) {
            addCriterion("email like", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailNotLike(String value) {
            addCriterion("email not like", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailIn(List<String> values) {
            addCriterion("email in", values, "email");
            return (Criteria) this;
        }

        public Criteria andEmailNotIn(List<String> values) {
            addCriterion("email not in", values, "email");
            return (Criteria) this;
        }

        public Criteria andEmailBetween(String value1, String value2) {
            addCriterion("email between", value1, value2, "email");
            return (Criteria) this;
        }

        public Criteria andEmailNotBetween(String value1, String value2) {
            addCriterion("email not between", value1, value2, "email");
            return (Criteria) this;
        }

        public Criteria andPlathformUserIdIsNull() {
            addCriterion("plathform_user_id is null");
            return (Criteria) this;
        }

        public Criteria andPlathformUserIdIsNotNull() {
            addCriterion("plathform_user_id is not null");
            return (Criteria) this;
        }

        public Criteria andPlathformUserIdEqualTo(String value) {
            addCriterion("plathform_user_id =", value, "plathformUserId");
            return (Criteria) this;
        }

        public Criteria andPlathformUserIdNotEqualTo(String value) {
            addCriterion("plathform_user_id <>", value, "plathformUserId");
            return (Criteria) this;
        }

        public Criteria andPlathformUserIdGreaterThan(String value) {
            addCriterion("plathform_user_id >", value, "plathformUserId");
            return (Criteria) this;
        }

        public Criteria andPlathformUserIdGreaterThanOrEqualTo(String value) {
            addCriterion("plathform_user_id >=", value, "plathformUserId");
            return (Criteria) this;
        }

        public Criteria andPlathformUserIdLessThan(String value) {
            addCriterion("plathform_user_id <", value, "plathformUserId");
            return (Criteria) this;
        }

        public Criteria andPlathformUserIdLessThanOrEqualTo(String value) {
            addCriterion("plathform_user_id <=", value, "plathformUserId");
            return (Criteria) this;
        }

        public Criteria andPlathformUserIdLike(String value) {
            addCriterion("plathform_user_id like", value, "plathformUserId");
            return (Criteria) this;
        }

        public Criteria andPlathformUserIdNotLike(String value) {
            addCriterion("plathform_user_id not like", value, "plathformUserId");
            return (Criteria) this;
        }

        public Criteria andPlathformUserIdIn(List<String> values) {
            addCriterion("plathform_user_id in", values, "plathformUserId");
            return (Criteria) this;
        }

        public Criteria andPlathformUserIdNotIn(List<String> values) {
            addCriterion("plathform_user_id not in", values, "plathformUserId");
            return (Criteria) this;
        }

        public Criteria andPlathformUserIdBetween(String value1, String value2) {
            addCriterion("plathform_user_id between", value1, value2, "plathformUserId");
            return (Criteria) this;
        }

        public Criteria andPlathformUserIdNotBetween(String value1, String value2) {
            addCriterion("plathform_user_id not between", value1, value2, "plathformUserId");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table busi_game_user
     *
     * @mbg.generated do_not_delete_during_merge Mon May 22 18:10:09 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table busi_game_user
     *
     * @mbg.generated Mon May 22 18:10:09 CST 2017
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}