package game2peer.mybatis.domain;

import java.math.BigDecimal;
import java.util.Date;

public class BusiUserAccountDetails {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column busi_user_account_details.id
     *
     * @mbg.generated Thu May 18 20:46:39 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column busi_user_account_details.user_id
     *
     * @mbg.generated Thu May 18 20:46:39 CST 2017
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column busi_user_account_details.game_id
     *
     * @mbg.generated Thu May 18 20:46:39 CST 2017
     */
    private String gameId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column busi_user_account_details.order_id
     *
     * @mbg.generated Thu May 18 20:46:39 CST 2017
     */
    private String orderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column busi_user_account_details.amount
     *
     * @mbg.generated Thu May 18 20:46:39 CST 2017
     */
    private BigDecimal amount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column busi_user_account_details.create_time
     *
     * @mbg.generated Thu May 18 20:46:39 CST 2017
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column busi_user_account_details.confirmed
     *
     * @mbg.generated Thu May 18 20:46:39 CST 2017
     */
    private Integer confirmed;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column busi_user_account_details.share_type
     *
     * @mbg.generated Thu May 18 20:46:39 CST 2017
     */
    private Integer shareType;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column busi_user_account_details.id
     *
     * @return the value of busi_user_account_details.id
     *
     * @mbg.generated Thu May 18 20:46:39 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column busi_user_account_details.id
     *
     * @param id the value for busi_user_account_details.id
     *
     * @mbg.generated Thu May 18 20:46:39 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column busi_user_account_details.user_id
     *
     * @return the value of busi_user_account_details.user_id
     *
     * @mbg.generated Thu May 18 20:46:39 CST 2017
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column busi_user_account_details.user_id
     *
     * @param userId the value for busi_user_account_details.user_id
     *
     * @mbg.generated Thu May 18 20:46:39 CST 2017
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column busi_user_account_details.game_id
     *
     * @return the value of busi_user_account_details.game_id
     *
     * @mbg.generated Thu May 18 20:46:39 CST 2017
     */
    public String getGameId() {
        return gameId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column busi_user_account_details.game_id
     *
     * @param gameId the value for busi_user_account_details.game_id
     *
     * @mbg.generated Thu May 18 20:46:39 CST 2017
     */
    public void setGameId(String gameId) {
        this.gameId = gameId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column busi_user_account_details.order_id
     *
     * @return the value of busi_user_account_details.order_id
     *
     * @mbg.generated Thu May 18 20:46:39 CST 2017
     */
    public String getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column busi_user_account_details.order_id
     *
     * @param orderId the value for busi_user_account_details.order_id
     *
     * @mbg.generated Thu May 18 20:46:39 CST 2017
     */
    public void setOrderId(String orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column busi_user_account_details.amount
     *
     * @return the value of busi_user_account_details.amount
     *
     * @mbg.generated Thu May 18 20:46:39 CST 2017
     */
    public BigDecimal getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column busi_user_account_details.amount
     *
     * @param amount the value for busi_user_account_details.amount
     *
     * @mbg.generated Thu May 18 20:46:39 CST 2017
     */
    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column busi_user_account_details.create_time
     *
     * @return the value of busi_user_account_details.create_time
     *
     * @mbg.generated Thu May 18 20:46:39 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column busi_user_account_details.create_time
     *
     * @param createTime the value for busi_user_account_details.create_time
     *
     * @mbg.generated Thu May 18 20:46:39 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column busi_user_account_details.confirmed
     *
     * @return the value of busi_user_account_details.confirmed
     *
     * @mbg.generated Thu May 18 20:46:39 CST 2017
     */
    public Integer getConfirmed() {
        return confirmed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column busi_user_account_details.confirmed
     *
     * @param confirmed the value for busi_user_account_details.confirmed
     *
     * @mbg.generated Thu May 18 20:46:39 CST 2017
     */
    public void setConfirmed(Integer confirmed) {
        this.confirmed = confirmed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column busi_user_account_details.share_type
     *
     * @return the value of busi_user_account_details.share_type
     *
     * @mbg.generated Thu May 18 20:46:39 CST 2017
     */
    public Integer getShareType() {
        return shareType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column busi_user_account_details.share_type
     *
     * @param shareType the value for busi_user_account_details.share_type
     *
     * @mbg.generated Thu May 18 20:46:39 CST 2017
     */
    public void setShareType(Integer shareType) {
        this.shareType = shareType;
    }
}