package game2peer.mybatis.domain;

import java.math.BigDecimal;
import java.util.Date;

public class BusiGamePayment extends BusiGamePaymentKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column busi_game_payment.game_user_id
     *
     * @mbg.generated Mon May 15 08:36:44 CST 2017
     */
    private String gameUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column busi_game_payment.login_name
     *
     * @mbg.generated Mon May 15 08:36:44 CST 2017
     */
    private String loginName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column busi_game_payment.createtime_in_game
     *
     * @mbg.generated Mon May 15 08:36:44 CST 2017
     */
    private Date createtimeInGame;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column busi_game_payment.amount
     *
     * @mbg.generated Mon May 15 08:36:44 CST 2017
     */
    private BigDecimal amount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column busi_game_payment.currency
     *
     * @mbg.generated Mon May 15 08:36:44 CST 2017
     */
    private String currency;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column busi_game_payment.coin
     *
     * @mbg.generated Mon May 15 08:36:44 CST 2017
     */
    private BigDecimal coin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column busi_game_payment.receive_time
     *
     * @mbg.generated Mon May 15 08:36:44 CST 2017
     */
    private Date receiveTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column busi_game_payment.invite_code
     *
     * @mbg.generated Mon May 15 08:36:44 CST 2017
     */
    private String inviteCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column busi_game_payment.error_code
     *
     * @mbg.generated Mon May 15 08:36:44 CST 2017
     */
    private Integer errorCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column busi_game_payment.mode
     *
     * @mbg.generated Mon May 15 08:36:44 CST 2017
     */
    private Integer mode;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column busi_game_payment.game_user_id
     *
     * @return the value of busi_game_payment.game_user_id
     *
     * @mbg.generated Mon May 15 08:36:44 CST 2017
     */
    public String getGameUserId() {
        return gameUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column busi_game_payment.game_user_id
     *
     * @param gameUserId the value for busi_game_payment.game_user_id
     *
     * @mbg.generated Mon May 15 08:36:44 CST 2017
     */
    public void setGameUserId(String gameUserId) {
        this.gameUserId = gameUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column busi_game_payment.login_name
     *
     * @return the value of busi_game_payment.login_name
     *
     * @mbg.generated Mon May 15 08:36:44 CST 2017
     */
    public String getLoginName() {
        return loginName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column busi_game_payment.login_name
     *
     * @param loginName the value for busi_game_payment.login_name
     *
     * @mbg.generated Mon May 15 08:36:44 CST 2017
     */
    public void setLoginName(String loginName) {
        this.loginName = loginName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column busi_game_payment.createtime_in_game
     *
     * @return the value of busi_game_payment.createtime_in_game
     *
     * @mbg.generated Mon May 15 08:36:44 CST 2017
     */
    public Date getCreatetimeInGame() {
        return createtimeInGame;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column busi_game_payment.createtime_in_game
     *
     * @param createtimeInGame the value for busi_game_payment.createtime_in_game
     *
     * @mbg.generated Mon May 15 08:36:44 CST 2017
     */
    public void setCreatetimeInGame(Date createtimeInGame) {
        this.createtimeInGame = createtimeInGame;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column busi_game_payment.amount
     *
     * @return the value of busi_game_payment.amount
     *
     * @mbg.generated Mon May 15 08:36:44 CST 2017
     */
    public BigDecimal getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column busi_game_payment.amount
     *
     * @param amount the value for busi_game_payment.amount
     *
     * @mbg.generated Mon May 15 08:36:44 CST 2017
     */
    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column busi_game_payment.currency
     *
     * @return the value of busi_game_payment.currency
     *
     * @mbg.generated Mon May 15 08:36:44 CST 2017
     */
    public String getCurrency() {
        return currency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column busi_game_payment.currency
     *
     * @param currency the value for busi_game_payment.currency
     *
     * @mbg.generated Mon May 15 08:36:44 CST 2017
     */
    public void setCurrency(String currency) {
        this.currency = currency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column busi_game_payment.coin
     *
     * @return the value of busi_game_payment.coin
     *
     * @mbg.generated Mon May 15 08:36:44 CST 2017
     */
    public BigDecimal getCoin() {
        return coin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column busi_game_payment.coin
     *
     * @param coin the value for busi_game_payment.coin
     *
     * @mbg.generated Mon May 15 08:36:44 CST 2017
     */
    public void setCoin(BigDecimal coin) {
        this.coin = coin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column busi_game_payment.receive_time
     *
     * @return the value of busi_game_payment.receive_time
     *
     * @mbg.generated Mon May 15 08:36:44 CST 2017
     */
    public Date getReceiveTime() {
        return receiveTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column busi_game_payment.receive_time
     *
     * @param receiveTime the value for busi_game_payment.receive_time
     *
     * @mbg.generated Mon May 15 08:36:44 CST 2017
     */
    public void setReceiveTime(Date receiveTime) {
        this.receiveTime = receiveTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column busi_game_payment.invite_code
     *
     * @return the value of busi_game_payment.invite_code
     *
     * @mbg.generated Mon May 15 08:36:44 CST 2017
     */
    public String getInviteCode() {
        return inviteCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column busi_game_payment.invite_code
     *
     * @param inviteCode the value for busi_game_payment.invite_code
     *
     * @mbg.generated Mon May 15 08:36:44 CST 2017
     */
    public void setInviteCode(String inviteCode) {
        this.inviteCode = inviteCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column busi_game_payment.error_code
     *
     * @return the value of busi_game_payment.error_code
     *
     * @mbg.generated Mon May 15 08:36:44 CST 2017
     */
    public Integer getErrorCode() {
        return errorCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column busi_game_payment.error_code
     *
     * @param errorCode the value for busi_game_payment.error_code
     *
     * @mbg.generated Mon May 15 08:36:44 CST 2017
     */
    public void setErrorCode(Integer errorCode) {
        this.errorCode = errorCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column busi_game_payment.mode
     *
     * @return the value of busi_game_payment.mode
     *
     * @mbg.generated Mon May 15 08:36:44 CST 2017
     */
    public Integer getMode() {
        return mode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column busi_game_payment.mode
     *
     * @param mode the value for busi_game_payment.mode
     *
     * @mbg.generated Mon May 15 08:36:44 CST 2017
     */
    public void setMode(Integer mode) {
        this.mode = mode;
    }
}