package game2peer.mybatis.domain;

import java.util.Date;

public class BusiUserLike extends BusiUserLikeKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column busi_user_like.create_time
     *
     * @mbg.generated Fri May 19 21:57:37 CST 2017
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column busi_user_like.create_time
     *
     * @return the value of busi_user_like.create_time
     *
     * @mbg.generated Fri May 19 21:57:37 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column busi_user_like.create_time
     *
     * @param createTime the value for busi_user_like.create_time
     *
     * @mbg.generated Fri May 19 21:57:37 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}