package game2peer.mybatis.domain;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class BusiUserAccountExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table busi_user_account
     *
     * @mbg.generated Thu May 18 20:46:39 CST 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table busi_user_account
     *
     * @mbg.generated Thu May 18 20:46:39 CST 2017
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table busi_user_account
     *
     * @mbg.generated Thu May 18 20:46:39 CST 2017
     */
    protected List<Criteria> oredCriteria;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table busi_user_account
     *
     * @mbg.generated Thu May 18 20:46:39 CST 2017
     */
    protected int limitStart = -1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table busi_user_account
     *
     * @mbg.generated Thu May 18 20:46:39 CST 2017
     */
    protected int limitEnd = -1;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table busi_user_account
     *
     * @mbg.generated Thu May 18 20:46:39 CST 2017
     */
    public BusiUserAccountExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table busi_user_account
     *
     * @mbg.generated Thu May 18 20:46:39 CST 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table busi_user_account
     *
     * @mbg.generated Thu May 18 20:46:39 CST 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table busi_user_account
     *
     * @mbg.generated Thu May 18 20:46:39 CST 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table busi_user_account
     *
     * @mbg.generated Thu May 18 20:46:39 CST 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table busi_user_account
     *
     * @mbg.generated Thu May 18 20:46:39 CST 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table busi_user_account
     *
     * @mbg.generated Thu May 18 20:46:39 CST 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table busi_user_account
     *
     * @mbg.generated Thu May 18 20:46:39 CST 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table busi_user_account
     *
     * @mbg.generated Thu May 18 20:46:39 CST 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table busi_user_account
     *
     * @mbg.generated Thu May 18 20:46:39 CST 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table busi_user_account
     *
     * @mbg.generated Thu May 18 20:46:39 CST 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table busi_user_account
     *
     * @mbg.generated Thu May 18 20:46:39 CST 2017
     */
    public void setLimitStart(int limitStart) {
        this.limitStart=limitStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table busi_user_account
     *
     * @mbg.generated Thu May 18 20:46:39 CST 2017
     */
    public int getLimitStart() {
        return limitStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table busi_user_account
     *
     * @mbg.generated Thu May 18 20:46:39 CST 2017
     */
    public void setLimitEnd(int limitEnd) {
        this.limitEnd=limitEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table busi_user_account
     *
     * @mbg.generated Thu May 18 20:46:39 CST 2017
     */
    public int getLimitEnd() {
        return limitEnd;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table busi_user_account
     *
     * @mbg.generated Thu May 18 20:46:39 CST 2017
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andUserIdIsNull() {
            addCriterion("user_id is null");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNotNull() {
            addCriterion("user_id is not null");
            return (Criteria) this;
        }

        public Criteria andUserIdEqualTo(String value) {
            addCriterion("user_id =", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotEqualTo(String value) {
            addCriterion("user_id <>", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThan(String value) {
            addCriterion("user_id >", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThanOrEqualTo(String value) {
            addCriterion("user_id >=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThan(String value) {
            addCriterion("user_id <", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThanOrEqualTo(String value) {
            addCriterion("user_id <=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLike(String value) {
            addCriterion("user_id like", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotLike(String value) {
            addCriterion("user_id not like", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdIn(List<String> values) {
            addCriterion("user_id in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotIn(List<String> values) {
            addCriterion("user_id not in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdBetween(String value1, String value2) {
            addCriterion("user_id between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotBetween(String value1, String value2) {
            addCriterion("user_id not between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andGameIdIsNull() {
            addCriterion("game_id is null");
            return (Criteria) this;
        }

        public Criteria andGameIdIsNotNull() {
            addCriterion("game_id is not null");
            return (Criteria) this;
        }

        public Criteria andGameIdEqualTo(String value) {
            addCriterion("game_id =", value, "gameId");
            return (Criteria) this;
        }

        public Criteria andGameIdNotEqualTo(String value) {
            addCriterion("game_id <>", value, "gameId");
            return (Criteria) this;
        }

        public Criteria andGameIdGreaterThan(String value) {
            addCriterion("game_id >", value, "gameId");
            return (Criteria) this;
        }

        public Criteria andGameIdGreaterThanOrEqualTo(String value) {
            addCriterion("game_id >=", value, "gameId");
            return (Criteria) this;
        }

        public Criteria andGameIdLessThan(String value) {
            addCriterion("game_id <", value, "gameId");
            return (Criteria) this;
        }

        public Criteria andGameIdLessThanOrEqualTo(String value) {
            addCriterion("game_id <=", value, "gameId");
            return (Criteria) this;
        }

        public Criteria andGameIdLike(String value) {
            addCriterion("game_id like", value, "gameId");
            return (Criteria) this;
        }

        public Criteria andGameIdNotLike(String value) {
            addCriterion("game_id not like", value, "gameId");
            return (Criteria) this;
        }

        public Criteria andGameIdIn(List<String> values) {
            addCriterion("game_id in", values, "gameId");
            return (Criteria) this;
        }

        public Criteria andGameIdNotIn(List<String> values) {
            addCriterion("game_id not in", values, "gameId");
            return (Criteria) this;
        }

        public Criteria andGameIdBetween(String value1, String value2) {
            addCriterion("game_id between", value1, value2, "gameId");
            return (Criteria) this;
        }

        public Criteria andGameIdNotBetween(String value1, String value2) {
            addCriterion("game_id not between", value1, value2, "gameId");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andIncomeConfirmedIsNull() {
            addCriterion("income_confirmed is null");
            return (Criteria) this;
        }

        public Criteria andIncomeConfirmedIsNotNull() {
            addCriterion("income_confirmed is not null");
            return (Criteria) this;
        }

        public Criteria andIncomeConfirmedEqualTo(BigDecimal value) {
            addCriterion("income_confirmed =", value, "incomeConfirmed");
            return (Criteria) this;
        }

        public Criteria andIncomeConfirmedNotEqualTo(BigDecimal value) {
            addCriterion("income_confirmed <>", value, "incomeConfirmed");
            return (Criteria) this;
        }

        public Criteria andIncomeConfirmedGreaterThan(BigDecimal value) {
            addCriterion("income_confirmed >", value, "incomeConfirmed");
            return (Criteria) this;
        }

        public Criteria andIncomeConfirmedGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("income_confirmed >=", value, "incomeConfirmed");
            return (Criteria) this;
        }

        public Criteria andIncomeConfirmedLessThan(BigDecimal value) {
            addCriterion("income_confirmed <", value, "incomeConfirmed");
            return (Criteria) this;
        }

        public Criteria andIncomeConfirmedLessThanOrEqualTo(BigDecimal value) {
            addCriterion("income_confirmed <=", value, "incomeConfirmed");
            return (Criteria) this;
        }

        public Criteria andIncomeConfirmedIn(List<BigDecimal> values) {
            addCriterion("income_confirmed in", values, "incomeConfirmed");
            return (Criteria) this;
        }

        public Criteria andIncomeConfirmedNotIn(List<BigDecimal> values) {
            addCriterion("income_confirmed not in", values, "incomeConfirmed");
            return (Criteria) this;
        }

        public Criteria andIncomeConfirmedBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("income_confirmed between", value1, value2, "incomeConfirmed");
            return (Criteria) this;
        }

        public Criteria andIncomeConfirmedNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("income_confirmed not between", value1, value2, "incomeConfirmed");
            return (Criteria) this;
        }

        public Criteria andIncomeNotConfirmedIsNull() {
            addCriterion("income_not_confirmed is null");
            return (Criteria) this;
        }

        public Criteria andIncomeNotConfirmedIsNotNull() {
            addCriterion("income_not_confirmed is not null");
            return (Criteria) this;
        }

        public Criteria andIncomeNotConfirmedEqualTo(BigDecimal value) {
            addCriterion("income_not_confirmed =", value, "incomeNotConfirmed");
            return (Criteria) this;
        }

        public Criteria andIncomeNotConfirmedNotEqualTo(BigDecimal value) {
            addCriterion("income_not_confirmed <>", value, "incomeNotConfirmed");
            return (Criteria) this;
        }

        public Criteria andIncomeNotConfirmedGreaterThan(BigDecimal value) {
            addCriterion("income_not_confirmed >", value, "incomeNotConfirmed");
            return (Criteria) this;
        }

        public Criteria andIncomeNotConfirmedGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("income_not_confirmed >=", value, "incomeNotConfirmed");
            return (Criteria) this;
        }

        public Criteria andIncomeNotConfirmedLessThan(BigDecimal value) {
            addCriterion("income_not_confirmed <", value, "incomeNotConfirmed");
            return (Criteria) this;
        }

        public Criteria andIncomeNotConfirmedLessThanOrEqualTo(BigDecimal value) {
            addCriterion("income_not_confirmed <=", value, "incomeNotConfirmed");
            return (Criteria) this;
        }

        public Criteria andIncomeNotConfirmedIn(List<BigDecimal> values) {
            addCriterion("income_not_confirmed in", values, "incomeNotConfirmed");
            return (Criteria) this;
        }

        public Criteria andIncomeNotConfirmedNotIn(List<BigDecimal> values) {
            addCriterion("income_not_confirmed not in", values, "incomeNotConfirmed");
            return (Criteria) this;
        }

        public Criteria andIncomeNotConfirmedBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("income_not_confirmed between", value1, value2, "incomeNotConfirmed");
            return (Criteria) this;
        }

        public Criteria andIncomeNotConfirmedNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("income_not_confirmed not between", value1, value2, "incomeNotConfirmed");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table busi_user_account
     *
     * @mbg.generated do_not_delete_during_merge Thu May 18 20:46:39 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table busi_user_account
     *
     * @mbg.generated Thu May 18 20:46:39 CST 2017
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}