package game2peer.mybatis.domain;

import java.math.BigDecimal;
import java.util.Date;

public class BusiGameProfits {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column busi_game_profits.id
     *
     * @mbg.generated Mon May 01 17:14:30 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column busi_game_profits.game_id
     *
     * @mbg.generated Mon May 01 17:14:30 CST 2017
     */
    private String gameId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column busi_game_profits.profit
     *
     * @mbg.generated Mon May 01 17:14:30 CST 2017
     */
    private BigDecimal profit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column busi_game_profits.profit_begin
     *
     * @mbg.generated Mon May 01 17:14:30 CST 2017
     */
    private Date profitBegin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column busi_game_profits.profit_end
     *
     * @mbg.generated Mon May 01 17:14:30 CST 2017
     */
    private Date profitEnd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column busi_game_profits.description
     *
     * @mbg.generated Mon May 01 17:14:30 CST 2017
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column busi_game_profits.cal_method
     *
     * @mbg.generated Mon May 01 17:14:30 CST 2017
     */
    private Integer calMethod;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column busi_game_profits.mode
     *
     * @mbg.generated Mon May 01 17:14:30 CST 2017
     */
    private Integer mode;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column busi_game_profits.id
     *
     * @return the value of busi_game_profits.id
     *
     * @mbg.generated Mon May 01 17:14:30 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column busi_game_profits.id
     *
     * @param id the value for busi_game_profits.id
     *
     * @mbg.generated Mon May 01 17:14:30 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column busi_game_profits.game_id
     *
     * @return the value of busi_game_profits.game_id
     *
     * @mbg.generated Mon May 01 17:14:30 CST 2017
     */
    public String getGameId() {
        return gameId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column busi_game_profits.game_id
     *
     * @param gameId the value for busi_game_profits.game_id
     *
     * @mbg.generated Mon May 01 17:14:30 CST 2017
     */
    public void setGameId(String gameId) {
        this.gameId = gameId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column busi_game_profits.profit
     *
     * @return the value of busi_game_profits.profit
     *
     * @mbg.generated Mon May 01 17:14:30 CST 2017
     */
    public BigDecimal getProfit() {
        return profit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column busi_game_profits.profit
     *
     * @param profit the value for busi_game_profits.profit
     *
     * @mbg.generated Mon May 01 17:14:30 CST 2017
     */
    public void setProfit(BigDecimal profit) {
        this.profit = profit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column busi_game_profits.profit_begin
     *
     * @return the value of busi_game_profits.profit_begin
     *
     * @mbg.generated Mon May 01 17:14:30 CST 2017
     */
    public Date getProfitBegin() {
        return profitBegin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column busi_game_profits.profit_begin
     *
     * @param profitBegin the value for busi_game_profits.profit_begin
     *
     * @mbg.generated Mon May 01 17:14:30 CST 2017
     */
    public void setProfitBegin(Date profitBegin) {
        this.profitBegin = profitBegin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column busi_game_profits.profit_end
     *
     * @return the value of busi_game_profits.profit_end
     *
     * @mbg.generated Mon May 01 17:14:30 CST 2017
     */
    public Date getProfitEnd() {
        return profitEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column busi_game_profits.profit_end
     *
     * @param profitEnd the value for busi_game_profits.profit_end
     *
     * @mbg.generated Mon May 01 17:14:30 CST 2017
     */
    public void setProfitEnd(Date profitEnd) {
        this.profitEnd = profitEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column busi_game_profits.description
     *
     * @return the value of busi_game_profits.description
     *
     * @mbg.generated Mon May 01 17:14:30 CST 2017
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column busi_game_profits.description
     *
     * @param description the value for busi_game_profits.description
     *
     * @mbg.generated Mon May 01 17:14:30 CST 2017
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column busi_game_profits.cal_method
     *
     * @return the value of busi_game_profits.cal_method
     *
     * @mbg.generated Mon May 01 17:14:30 CST 2017
     */
    public Integer getCalMethod() {
        return calMethod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column busi_game_profits.cal_method
     *
     * @param calMethod the value for busi_game_profits.cal_method
     *
     * @mbg.generated Mon May 01 17:14:30 CST 2017
     */
    public void setCalMethod(Integer calMethod) {
        this.calMethod = calMethod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column busi_game_profits.mode
     *
     * @return the value of busi_game_profits.mode
     *
     * @mbg.generated Mon May 01 17:14:30 CST 2017
     */
    public Integer getMode() {
        return mode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column busi_game_profits.mode
     *
     * @param mode the value for busi_game_profits.mode
     *
     * @mbg.generated Mon May 01 17:14:30 CST 2017
     */
    public void setMode(Integer mode) {
        this.mode = mode;
    }
}