package game2peer.mybatis.domain;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class BusiGameExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table busi_game
     *
     * @mbg.generated Mon May 15 08:36:44 CST 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table busi_game
     *
     * @mbg.generated Mon May 15 08:36:44 CST 2017
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table busi_game
     *
     * @mbg.generated Mon May 15 08:36:44 CST 2017
     */
    protected List<Criteria> oredCriteria;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table busi_game
     *
     * @mbg.generated Mon May 15 08:36:44 CST 2017
     */
    protected int limitStart = -1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table busi_game
     *
     * @mbg.generated Mon May 15 08:36:44 CST 2017
     */
    protected int limitEnd = -1;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table busi_game
     *
     * @mbg.generated Mon May 15 08:36:44 CST 2017
     */
    public BusiGameExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table busi_game
     *
     * @mbg.generated Mon May 15 08:36:44 CST 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table busi_game
     *
     * @mbg.generated Mon May 15 08:36:44 CST 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table busi_game
     *
     * @mbg.generated Mon May 15 08:36:44 CST 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table busi_game
     *
     * @mbg.generated Mon May 15 08:36:44 CST 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table busi_game
     *
     * @mbg.generated Mon May 15 08:36:44 CST 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table busi_game
     *
     * @mbg.generated Mon May 15 08:36:44 CST 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table busi_game
     *
     * @mbg.generated Mon May 15 08:36:44 CST 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table busi_game
     *
     * @mbg.generated Mon May 15 08:36:44 CST 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table busi_game
     *
     * @mbg.generated Mon May 15 08:36:44 CST 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table busi_game
     *
     * @mbg.generated Mon May 15 08:36:44 CST 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table busi_game
     *
     * @mbg.generated Mon May 15 08:36:44 CST 2017
     */
    public void setLimitStart(int limitStart) {
        this.limitStart=limitStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table busi_game
     *
     * @mbg.generated Mon May 15 08:36:44 CST 2017
     */
    public int getLimitStart() {
        return limitStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table busi_game
     *
     * @mbg.generated Mon May 15 08:36:44 CST 2017
     */
    public void setLimitEnd(int limitEnd) {
        this.limitEnd=limitEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table busi_game
     *
     * @mbg.generated Mon May 15 08:36:44 CST 2017
     */
    public int getLimitEnd() {
        return limitEnd;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table busi_game
     *
     * @mbg.generated Mon May 15 08:36:44 CST 2017
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(String value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(String value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(String value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(String value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(String value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(String value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLike(String value) {
            addCriterion("id like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotLike(String value) {
            addCriterion("id not like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<String> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<String> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(String value1, String value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(String value1, String value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNull() {
            addCriterion("user_id is null");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNotNull() {
            addCriterion("user_id is not null");
            return (Criteria) this;
        }

        public Criteria andUserIdEqualTo(String value) {
            addCriterion("user_id =", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotEqualTo(String value) {
            addCriterion("user_id <>", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThan(String value) {
            addCriterion("user_id >", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThanOrEqualTo(String value) {
            addCriterion("user_id >=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThan(String value) {
            addCriterion("user_id <", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThanOrEqualTo(String value) {
            addCriterion("user_id <=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLike(String value) {
            addCriterion("user_id like", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotLike(String value) {
            addCriterion("user_id not like", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdIn(List<String> values) {
            addCriterion("user_id in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotIn(List<String> values) {
            addCriterion("user_id not in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdBetween(String value1, String value2) {
            addCriterion("user_id between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotBetween(String value1, String value2) {
            addCriterion("user_id not between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andGameNameIsNull() {
            addCriterion("game_name is null");
            return (Criteria) this;
        }

        public Criteria andGameNameIsNotNull() {
            addCriterion("game_name is not null");
            return (Criteria) this;
        }

        public Criteria andGameNameEqualTo(String value) {
            addCriterion("game_name =", value, "gameName");
            return (Criteria) this;
        }

        public Criteria andGameNameNotEqualTo(String value) {
            addCriterion("game_name <>", value, "gameName");
            return (Criteria) this;
        }

        public Criteria andGameNameGreaterThan(String value) {
            addCriterion("game_name >", value, "gameName");
            return (Criteria) this;
        }

        public Criteria andGameNameGreaterThanOrEqualTo(String value) {
            addCriterion("game_name >=", value, "gameName");
            return (Criteria) this;
        }

        public Criteria andGameNameLessThan(String value) {
            addCriterion("game_name <", value, "gameName");
            return (Criteria) this;
        }

        public Criteria andGameNameLessThanOrEqualTo(String value) {
            addCriterion("game_name <=", value, "gameName");
            return (Criteria) this;
        }

        public Criteria andGameNameLike(String value) {
            addCriterion("game_name like", value, "gameName");
            return (Criteria) this;
        }

        public Criteria andGameNameNotLike(String value) {
            addCriterion("game_name not like", value, "gameName");
            return (Criteria) this;
        }

        public Criteria andGameNameIn(List<String> values) {
            addCriterion("game_name in", values, "gameName");
            return (Criteria) this;
        }

        public Criteria andGameNameNotIn(List<String> values) {
            addCriterion("game_name not in", values, "gameName");
            return (Criteria) this;
        }

        public Criteria andGameNameBetween(String value1, String value2) {
            addCriterion("game_name between", value1, value2, "gameName");
            return (Criteria) this;
        }

        public Criteria andGameNameNotBetween(String value1, String value2) {
            addCriterion("game_name not between", value1, value2, "gameName");
            return (Criteria) this;
        }

        public Criteria andLangIsNull() {
            addCriterion("lang is null");
            return (Criteria) this;
        }

        public Criteria andLangIsNotNull() {
            addCriterion("lang is not null");
            return (Criteria) this;
        }

        public Criteria andLangEqualTo(String value) {
            addCriterion("lang =", value, "lang");
            return (Criteria) this;
        }

        public Criteria andLangNotEqualTo(String value) {
            addCriterion("lang <>", value, "lang");
            return (Criteria) this;
        }

        public Criteria andLangGreaterThan(String value) {
            addCriterion("lang >", value, "lang");
            return (Criteria) this;
        }

        public Criteria andLangGreaterThanOrEqualTo(String value) {
            addCriterion("lang >=", value, "lang");
            return (Criteria) this;
        }

        public Criteria andLangLessThan(String value) {
            addCriterion("lang <", value, "lang");
            return (Criteria) this;
        }

        public Criteria andLangLessThanOrEqualTo(String value) {
            addCriterion("lang <=", value, "lang");
            return (Criteria) this;
        }

        public Criteria andLangLike(String value) {
            addCriterion("lang like", value, "lang");
            return (Criteria) this;
        }

        public Criteria andLangNotLike(String value) {
            addCriterion("lang not like", value, "lang");
            return (Criteria) this;
        }

        public Criteria andLangIn(List<String> values) {
            addCriterion("lang in", values, "lang");
            return (Criteria) this;
        }

        public Criteria andLangNotIn(List<String> values) {
            addCriterion("lang not in", values, "lang");
            return (Criteria) this;
        }

        public Criteria andLangBetween(String value1, String value2) {
            addCriterion("lang between", value1, value2, "lang");
            return (Criteria) this;
        }

        public Criteria andLangNotBetween(String value1, String value2) {
            addCriterion("lang not between", value1, value2, "lang");
            return (Criteria) this;
        }

        public Criteria andLogoIsNull() {
            addCriterion("logo is null");
            return (Criteria) this;
        }

        public Criteria andLogoIsNotNull() {
            addCriterion("logo is not null");
            return (Criteria) this;
        }

        public Criteria andLogoEqualTo(String value) {
            addCriterion("logo =", value, "logo");
            return (Criteria) this;
        }

        public Criteria andLogoNotEqualTo(String value) {
            addCriterion("logo <>", value, "logo");
            return (Criteria) this;
        }

        public Criteria andLogoGreaterThan(String value) {
            addCriterion("logo >", value, "logo");
            return (Criteria) this;
        }

        public Criteria andLogoGreaterThanOrEqualTo(String value) {
            addCriterion("logo >=", value, "logo");
            return (Criteria) this;
        }

        public Criteria andLogoLessThan(String value) {
            addCriterion("logo <", value, "logo");
            return (Criteria) this;
        }

        public Criteria andLogoLessThanOrEqualTo(String value) {
            addCriterion("logo <=", value, "logo");
            return (Criteria) this;
        }

        public Criteria andLogoLike(String value) {
            addCriterion("logo like", value, "logo");
            return (Criteria) this;
        }

        public Criteria andLogoNotLike(String value) {
            addCriterion("logo not like", value, "logo");
            return (Criteria) this;
        }

        public Criteria andLogoIn(List<String> values) {
            addCriterion("logo in", values, "logo");
            return (Criteria) this;
        }

        public Criteria andLogoNotIn(List<String> values) {
            addCriterion("logo not in", values, "logo");
            return (Criteria) this;
        }

        public Criteria andLogoBetween(String value1, String value2) {
            addCriterion("logo between", value1, value2, "logo");
            return (Criteria) this;
        }

        public Criteria andLogoNotBetween(String value1, String value2) {
            addCriterion("logo not between", value1, value2, "logo");
            return (Criteria) this;
        }

        public Criteria andCoverImageIsNull() {
            addCriterion("cover_image is null");
            return (Criteria) this;
        }

        public Criteria andCoverImageIsNotNull() {
            addCriterion("cover_image is not null");
            return (Criteria) this;
        }

        public Criteria andCoverImageEqualTo(String value) {
            addCriterion("cover_image =", value, "coverImage");
            return (Criteria) this;
        }

        public Criteria andCoverImageNotEqualTo(String value) {
            addCriterion("cover_image <>", value, "coverImage");
            return (Criteria) this;
        }

        public Criteria andCoverImageGreaterThan(String value) {
            addCriterion("cover_image >", value, "coverImage");
            return (Criteria) this;
        }

        public Criteria andCoverImageGreaterThanOrEqualTo(String value) {
            addCriterion("cover_image >=", value, "coverImage");
            return (Criteria) this;
        }

        public Criteria andCoverImageLessThan(String value) {
            addCriterion("cover_image <", value, "coverImage");
            return (Criteria) this;
        }

        public Criteria andCoverImageLessThanOrEqualTo(String value) {
            addCriterion("cover_image <=", value, "coverImage");
            return (Criteria) this;
        }

        public Criteria andCoverImageLike(String value) {
            addCriterion("cover_image like", value, "coverImage");
            return (Criteria) this;
        }

        public Criteria andCoverImageNotLike(String value) {
            addCriterion("cover_image not like", value, "coverImage");
            return (Criteria) this;
        }

        public Criteria andCoverImageIn(List<String> values) {
            addCriterion("cover_image in", values, "coverImage");
            return (Criteria) this;
        }

        public Criteria andCoverImageNotIn(List<String> values) {
            addCriterion("cover_image not in", values, "coverImage");
            return (Criteria) this;
        }

        public Criteria andCoverImageBetween(String value1, String value2) {
            addCriterion("cover_image between", value1, value2, "coverImage");
            return (Criteria) this;
        }

        public Criteria andCoverImageNotBetween(String value1, String value2) {
            addCriterion("cover_image not between", value1, value2, "coverImage");
            return (Criteria) this;
        }

        public Criteria andSummaryIsNull() {
            addCriterion("summary is null");
            return (Criteria) this;
        }

        public Criteria andSummaryIsNotNull() {
            addCriterion("summary is not null");
            return (Criteria) this;
        }

        public Criteria andSummaryEqualTo(String value) {
            addCriterion("summary =", value, "summary");
            return (Criteria) this;
        }

        public Criteria andSummaryNotEqualTo(String value) {
            addCriterion("summary <>", value, "summary");
            return (Criteria) this;
        }

        public Criteria andSummaryGreaterThan(String value) {
            addCriterion("summary >", value, "summary");
            return (Criteria) this;
        }

        public Criteria andSummaryGreaterThanOrEqualTo(String value) {
            addCriterion("summary >=", value, "summary");
            return (Criteria) this;
        }

        public Criteria andSummaryLessThan(String value) {
            addCriterion("summary <", value, "summary");
            return (Criteria) this;
        }

        public Criteria andSummaryLessThanOrEqualTo(String value) {
            addCriterion("summary <=", value, "summary");
            return (Criteria) this;
        }

        public Criteria andSummaryLike(String value) {
            addCriterion("summary like", value, "summary");
            return (Criteria) this;
        }

        public Criteria andSummaryNotLike(String value) {
            addCriterion("summary not like", value, "summary");
            return (Criteria) this;
        }

        public Criteria andSummaryIn(List<String> values) {
            addCriterion("summary in", values, "summary");
            return (Criteria) this;
        }

        public Criteria andSummaryNotIn(List<String> values) {
            addCriterion("summary not in", values, "summary");
            return (Criteria) this;
        }

        public Criteria andSummaryBetween(String value1, String value2) {
            addCriterion("summary between", value1, value2, "summary");
            return (Criteria) this;
        }

        public Criteria andSummaryNotBetween(String value1, String value2) {
            addCriterion("summary not between", value1, value2, "summary");
            return (Criteria) this;
        }

        public Criteria andRecommendedIsNull() {
            addCriterion("recommended is null");
            return (Criteria) this;
        }

        public Criteria andRecommendedIsNotNull() {
            addCriterion("recommended is not null");
            return (Criteria) this;
        }

        public Criteria andRecommendedEqualTo(Integer value) {
            addCriterion("recommended =", value, "recommended");
            return (Criteria) this;
        }

        public Criteria andRecommendedNotEqualTo(Integer value) {
            addCriterion("recommended <>", value, "recommended");
            return (Criteria) this;
        }

        public Criteria andRecommendedGreaterThan(Integer value) {
            addCriterion("recommended >", value, "recommended");
            return (Criteria) this;
        }

        public Criteria andRecommendedGreaterThanOrEqualTo(Integer value) {
            addCriterion("recommended >=", value, "recommended");
            return (Criteria) this;
        }

        public Criteria andRecommendedLessThan(Integer value) {
            addCriterion("recommended <", value, "recommended");
            return (Criteria) this;
        }

        public Criteria andRecommendedLessThanOrEqualTo(Integer value) {
            addCriterion("recommended <=", value, "recommended");
            return (Criteria) this;
        }

        public Criteria andRecommendedIn(List<Integer> values) {
            addCriterion("recommended in", values, "recommended");
            return (Criteria) this;
        }

        public Criteria andRecommendedNotIn(List<Integer> values) {
            addCriterion("recommended not in", values, "recommended");
            return (Criteria) this;
        }

        public Criteria andRecommendedBetween(Integer value1, Integer value2) {
            addCriterion("recommended between", value1, value2, "recommended");
            return (Criteria) this;
        }

        public Criteria andRecommendedNotBetween(Integer value1, Integer value2) {
            addCriterion("recommended not between", value1, value2, "recommended");
            return (Criteria) this;
        }

        public Criteria andCreateDateIsNull() {
            addCriterion("create_date is null");
            return (Criteria) this;
        }

        public Criteria andCreateDateIsNotNull() {
            addCriterion("create_date is not null");
            return (Criteria) this;
        }

        public Criteria andCreateDateEqualTo(Date value) {
            addCriterion("create_date =", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotEqualTo(Date value) {
            addCriterion("create_date <>", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateGreaterThan(Date value) {
            addCriterion("create_date >", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateGreaterThanOrEqualTo(Date value) {
            addCriterion("create_date >=", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateLessThan(Date value) {
            addCriterion("create_date <", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateLessThanOrEqualTo(Date value) {
            addCriterion("create_date <=", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateIn(List<Date> values) {
            addCriterion("create_date in", values, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotIn(List<Date> values) {
            addCriterion("create_date not in", values, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateBetween(Date value1, Date value2) {
            addCriterion("create_date between", value1, value2, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotBetween(Date value1, Date value2) {
            addCriterion("create_date not between", value1, value2, "createDate");
            return (Criteria) this;
        }

        public Criteria andRegisterCallbackIsNull() {
            addCriterion("register_callback is null");
            return (Criteria) this;
        }

        public Criteria andRegisterCallbackIsNotNull() {
            addCriterion("register_callback is not null");
            return (Criteria) this;
        }

        public Criteria andRegisterCallbackEqualTo(String value) {
            addCriterion("register_callback =", value, "registerCallback");
            return (Criteria) this;
        }

        public Criteria andRegisterCallbackNotEqualTo(String value) {
            addCriterion("register_callback <>", value, "registerCallback");
            return (Criteria) this;
        }

        public Criteria andRegisterCallbackGreaterThan(String value) {
            addCriterion("register_callback >", value, "registerCallback");
            return (Criteria) this;
        }

        public Criteria andRegisterCallbackGreaterThanOrEqualTo(String value) {
            addCriterion("register_callback >=", value, "registerCallback");
            return (Criteria) this;
        }

        public Criteria andRegisterCallbackLessThan(String value) {
            addCriterion("register_callback <", value, "registerCallback");
            return (Criteria) this;
        }

        public Criteria andRegisterCallbackLessThanOrEqualTo(String value) {
            addCriterion("register_callback <=", value, "registerCallback");
            return (Criteria) this;
        }

        public Criteria andRegisterCallbackLike(String value) {
            addCriterion("register_callback like", value, "registerCallback");
            return (Criteria) this;
        }

        public Criteria andRegisterCallbackNotLike(String value) {
            addCriterion("register_callback not like", value, "registerCallback");
            return (Criteria) this;
        }

        public Criteria andRegisterCallbackIn(List<String> values) {
            addCriterion("register_callback in", values, "registerCallback");
            return (Criteria) this;
        }

        public Criteria andRegisterCallbackNotIn(List<String> values) {
            addCriterion("register_callback not in", values, "registerCallback");
            return (Criteria) this;
        }

        public Criteria andRegisterCallbackBetween(String value1, String value2) {
            addCriterion("register_callback between", value1, value2, "registerCallback");
            return (Criteria) this;
        }

        public Criteria andRegisterCallbackNotBetween(String value1, String value2) {
            addCriterion("register_callback not between", value1, value2, "registerCallback");
            return (Criteria) this;
        }

        public Criteria andRegisterUiIsNull() {
            addCriterion("register_ui is null");
            return (Criteria) this;
        }

        public Criteria andRegisterUiIsNotNull() {
            addCriterion("register_ui is not null");
            return (Criteria) this;
        }

        public Criteria andRegisterUiEqualTo(Integer value) {
            addCriterion("register_ui =", value, "registerUi");
            return (Criteria) this;
        }

        public Criteria andRegisterUiNotEqualTo(Integer value) {
            addCriterion("register_ui <>", value, "registerUi");
            return (Criteria) this;
        }

        public Criteria andRegisterUiGreaterThan(Integer value) {
            addCriterion("register_ui >", value, "registerUi");
            return (Criteria) this;
        }

        public Criteria andRegisterUiGreaterThanOrEqualTo(Integer value) {
            addCriterion("register_ui >=", value, "registerUi");
            return (Criteria) this;
        }

        public Criteria andRegisterUiLessThan(Integer value) {
            addCriterion("register_ui <", value, "registerUi");
            return (Criteria) this;
        }

        public Criteria andRegisterUiLessThanOrEqualTo(Integer value) {
            addCriterion("register_ui <=", value, "registerUi");
            return (Criteria) this;
        }

        public Criteria andRegisterUiIn(List<Integer> values) {
            addCriterion("register_ui in", values, "registerUi");
            return (Criteria) this;
        }

        public Criteria andRegisterUiNotIn(List<Integer> values) {
            addCriterion("register_ui not in", values, "registerUi");
            return (Criteria) this;
        }

        public Criteria andRegisterUiBetween(Integer value1, Integer value2) {
            addCriterion("register_ui between", value1, value2, "registerUi");
            return (Criteria) this;
        }

        public Criteria andRegisterUiNotBetween(Integer value1, Integer value2) {
            addCriterion("register_ui not between", value1, value2, "registerUi");
            return (Criteria) this;
        }

        public Criteria andRegisterWithDomainIsNull() {
            addCriterion("register_with_domain is null");
            return (Criteria) this;
        }

        public Criteria andRegisterWithDomainIsNotNull() {
            addCriterion("register_with_domain is not null");
            return (Criteria) this;
        }

        public Criteria andRegisterWithDomainEqualTo(String value) {
            addCriterion("register_with_domain =", value, "registerWithDomain");
            return (Criteria) this;
        }

        public Criteria andRegisterWithDomainNotEqualTo(String value) {
            addCriterion("register_with_domain <>", value, "registerWithDomain");
            return (Criteria) this;
        }

        public Criteria andRegisterWithDomainGreaterThan(String value) {
            addCriterion("register_with_domain >", value, "registerWithDomain");
            return (Criteria) this;
        }

        public Criteria andRegisterWithDomainGreaterThanOrEqualTo(String value) {
            addCriterion("register_with_domain >=", value, "registerWithDomain");
            return (Criteria) this;
        }

        public Criteria andRegisterWithDomainLessThan(String value) {
            addCriterion("register_with_domain <", value, "registerWithDomain");
            return (Criteria) this;
        }

        public Criteria andRegisterWithDomainLessThanOrEqualTo(String value) {
            addCriterion("register_with_domain <=", value, "registerWithDomain");
            return (Criteria) this;
        }

        public Criteria andRegisterWithDomainLike(String value) {
            addCriterion("register_with_domain like", value, "registerWithDomain");
            return (Criteria) this;
        }

        public Criteria andRegisterWithDomainNotLike(String value) {
            addCriterion("register_with_domain not like", value, "registerWithDomain");
            return (Criteria) this;
        }

        public Criteria andRegisterWithDomainIn(List<String> values) {
            addCriterion("register_with_domain in", values, "registerWithDomain");
            return (Criteria) this;
        }

        public Criteria andRegisterWithDomainNotIn(List<String> values) {
            addCriterion("register_with_domain not in", values, "registerWithDomain");
            return (Criteria) this;
        }

        public Criteria andRegisterWithDomainBetween(String value1, String value2) {
            addCriterion("register_with_domain between", value1, value2, "registerWithDomain");
            return (Criteria) this;
        }

        public Criteria andRegisterWithDomainNotBetween(String value1, String value2) {
            addCriterion("register_with_domain not between", value1, value2, "registerWithDomain");
            return (Criteria) this;
        }

        public Criteria andRegisterPasswordTypeIsNull() {
            addCriterion("register_password_type is null");
            return (Criteria) this;
        }

        public Criteria andRegisterPasswordTypeIsNotNull() {
            addCriterion("register_password_type is not null");
            return (Criteria) this;
        }

        public Criteria andRegisterPasswordTypeEqualTo(Integer value) {
            addCriterion("register_password_type =", value, "registerPasswordType");
            return (Criteria) this;
        }

        public Criteria andRegisterPasswordTypeNotEqualTo(Integer value) {
            addCriterion("register_password_type <>", value, "registerPasswordType");
            return (Criteria) this;
        }

        public Criteria andRegisterPasswordTypeGreaterThan(Integer value) {
            addCriterion("register_password_type >", value, "registerPasswordType");
            return (Criteria) this;
        }

        public Criteria andRegisterPasswordTypeGreaterThanOrEqualTo(Integer value) {
            addCriterion("register_password_type >=", value, "registerPasswordType");
            return (Criteria) this;
        }

        public Criteria andRegisterPasswordTypeLessThan(Integer value) {
            addCriterion("register_password_type <", value, "registerPasswordType");
            return (Criteria) this;
        }

        public Criteria andRegisterPasswordTypeLessThanOrEqualTo(Integer value) {
            addCriterion("register_password_type <=", value, "registerPasswordType");
            return (Criteria) this;
        }

        public Criteria andRegisterPasswordTypeIn(List<Integer> values) {
            addCriterion("register_password_type in", values, "registerPasswordType");
            return (Criteria) this;
        }

        public Criteria andRegisterPasswordTypeNotIn(List<Integer> values) {
            addCriterion("register_password_type not in", values, "registerPasswordType");
            return (Criteria) this;
        }

        public Criteria andRegisterPasswordTypeBetween(Integer value1, Integer value2) {
            addCriterion("register_password_type between", value1, value2, "registerPasswordType");
            return (Criteria) this;
        }

        public Criteria andRegisterPasswordTypeNotBetween(Integer value1, Integer value2) {
            addCriterion("register_password_type not between", value1, value2, "registerPasswordType");
            return (Criteria) this;
        }

        public Criteria andDownloadPageIsNull() {
            addCriterion("download_page is null");
            return (Criteria) this;
        }

        public Criteria andDownloadPageIsNotNull() {
            addCriterion("download_page is not null");
            return (Criteria) this;
        }

        public Criteria andDownloadPageEqualTo(String value) {
            addCriterion("download_page =", value, "downloadPage");
            return (Criteria) this;
        }

        public Criteria andDownloadPageNotEqualTo(String value) {
            addCriterion("download_page <>", value, "downloadPage");
            return (Criteria) this;
        }

        public Criteria andDownloadPageGreaterThan(String value) {
            addCriterion("download_page >", value, "downloadPage");
            return (Criteria) this;
        }

        public Criteria andDownloadPageGreaterThanOrEqualTo(String value) {
            addCriterion("download_page >=", value, "downloadPage");
            return (Criteria) this;
        }

        public Criteria andDownloadPageLessThan(String value) {
            addCriterion("download_page <", value, "downloadPage");
            return (Criteria) this;
        }

        public Criteria andDownloadPageLessThanOrEqualTo(String value) {
            addCriterion("download_page <=", value, "downloadPage");
            return (Criteria) this;
        }

        public Criteria andDownloadPageLike(String value) {
            addCriterion("download_page like", value, "downloadPage");
            return (Criteria) this;
        }

        public Criteria andDownloadPageNotLike(String value) {
            addCriterion("download_page not like", value, "downloadPage");
            return (Criteria) this;
        }

        public Criteria andDownloadPageIn(List<String> values) {
            addCriterion("download_page in", values, "downloadPage");
            return (Criteria) this;
        }

        public Criteria andDownloadPageNotIn(List<String> values) {
            addCriterion("download_page not in", values, "downloadPage");
            return (Criteria) this;
        }

        public Criteria andDownloadPageBetween(String value1, String value2) {
            addCriterion("download_page between", value1, value2, "downloadPage");
            return (Criteria) this;
        }

        public Criteria andDownloadPageNotBetween(String value1, String value2) {
            addCriterion("download_page not between", value1, value2, "downloadPage");
            return (Criteria) this;
        }

        public Criteria andGameKeyIsNull() {
            addCriterion("game_key is null");
            return (Criteria) this;
        }

        public Criteria andGameKeyIsNotNull() {
            addCriterion("game_key is not null");
            return (Criteria) this;
        }

        public Criteria andGameKeyEqualTo(String value) {
            addCriterion("game_key =", value, "gameKey");
            return (Criteria) this;
        }

        public Criteria andGameKeyNotEqualTo(String value) {
            addCriterion("game_key <>", value, "gameKey");
            return (Criteria) this;
        }

        public Criteria andGameKeyGreaterThan(String value) {
            addCriterion("game_key >", value, "gameKey");
            return (Criteria) this;
        }

        public Criteria andGameKeyGreaterThanOrEqualTo(String value) {
            addCriterion("game_key >=", value, "gameKey");
            return (Criteria) this;
        }

        public Criteria andGameKeyLessThan(String value) {
            addCriterion("game_key <", value, "gameKey");
            return (Criteria) this;
        }

        public Criteria andGameKeyLessThanOrEqualTo(String value) {
            addCriterion("game_key <=", value, "gameKey");
            return (Criteria) this;
        }

        public Criteria andGameKeyLike(String value) {
            addCriterion("game_key like", value, "gameKey");
            return (Criteria) this;
        }

        public Criteria andGameKeyNotLike(String value) {
            addCriterion("game_key not like", value, "gameKey");
            return (Criteria) this;
        }

        public Criteria andGameKeyIn(List<String> values) {
            addCriterion("game_key in", values, "gameKey");
            return (Criteria) this;
        }

        public Criteria andGameKeyNotIn(List<String> values) {
            addCriterion("game_key not in", values, "gameKey");
            return (Criteria) this;
        }

        public Criteria andGameKeyBetween(String value1, String value2) {
            addCriterion("game_key between", value1, value2, "gameKey");
            return (Criteria) this;
        }

        public Criteria andGameKeyNotBetween(String value1, String value2) {
            addCriterion("game_key not between", value1, value2, "gameKey");
            return (Criteria) this;
        }

        public Criteria andPayAmountIsNull() {
            addCriterion("pay_amount is null");
            return (Criteria) this;
        }

        public Criteria andPayAmountIsNotNull() {
            addCriterion("pay_amount is not null");
            return (Criteria) this;
        }

        public Criteria andPayAmountEqualTo(BigDecimal value) {
            addCriterion("pay_amount =", value, "payAmount");
            return (Criteria) this;
        }

        public Criteria andPayAmountNotEqualTo(BigDecimal value) {
            addCriterion("pay_amount <>", value, "payAmount");
            return (Criteria) this;
        }

        public Criteria andPayAmountGreaterThan(BigDecimal value) {
            addCriterion("pay_amount >", value, "payAmount");
            return (Criteria) this;
        }

        public Criteria andPayAmountGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("pay_amount >=", value, "payAmount");
            return (Criteria) this;
        }

        public Criteria andPayAmountLessThan(BigDecimal value) {
            addCriterion("pay_amount <", value, "payAmount");
            return (Criteria) this;
        }

        public Criteria andPayAmountLessThanOrEqualTo(BigDecimal value) {
            addCriterion("pay_amount <=", value, "payAmount");
            return (Criteria) this;
        }

        public Criteria andPayAmountIn(List<BigDecimal> values) {
            addCriterion("pay_amount in", values, "payAmount");
            return (Criteria) this;
        }

        public Criteria andPayAmountNotIn(List<BigDecimal> values) {
            addCriterion("pay_amount not in", values, "payAmount");
            return (Criteria) this;
        }

        public Criteria andPayAmountBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("pay_amount between", value1, value2, "payAmount");
            return (Criteria) this;
        }

        public Criteria andPayAmountNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("pay_amount not between", value1, value2, "payAmount");
            return (Criteria) this;
        }

        public Criteria andGameUsersIsNull() {
            addCriterion("game_users is null");
            return (Criteria) this;
        }

        public Criteria andGameUsersIsNotNull() {
            addCriterion("game_users is not null");
            return (Criteria) this;
        }

        public Criteria andGameUsersEqualTo(Integer value) {
            addCriterion("game_users =", value, "gameUsers");
            return (Criteria) this;
        }

        public Criteria andGameUsersNotEqualTo(Integer value) {
            addCriterion("game_users <>", value, "gameUsers");
            return (Criteria) this;
        }

        public Criteria andGameUsersGreaterThan(Integer value) {
            addCriterion("game_users >", value, "gameUsers");
            return (Criteria) this;
        }

        public Criteria andGameUsersGreaterThanOrEqualTo(Integer value) {
            addCriterion("game_users >=", value, "gameUsers");
            return (Criteria) this;
        }

        public Criteria andGameUsersLessThan(Integer value) {
            addCriterion("game_users <", value, "gameUsers");
            return (Criteria) this;
        }

        public Criteria andGameUsersLessThanOrEqualTo(Integer value) {
            addCriterion("game_users <=", value, "gameUsers");
            return (Criteria) this;
        }

        public Criteria andGameUsersIn(List<Integer> values) {
            addCriterion("game_users in", values, "gameUsers");
            return (Criteria) this;
        }

        public Criteria andGameUsersNotIn(List<Integer> values) {
            addCriterion("game_users not in", values, "gameUsers");
            return (Criteria) this;
        }

        public Criteria andGameUsersBetween(Integer value1, Integer value2) {
            addCriterion("game_users between", value1, value2, "gameUsers");
            return (Criteria) this;
        }

        public Criteria andGameUsersNotBetween(Integer value1, Integer value2) {
            addCriterion("game_users not between", value1, value2, "gameUsers");
            return (Criteria) this;
        }

        public Criteria andModeIsNull() {
            addCriterion("mode is null");
            return (Criteria) this;
        }

        public Criteria andModeIsNotNull() {
            addCriterion("mode is not null");
            return (Criteria) this;
        }

        public Criteria andModeEqualTo(Integer value) {
            addCriterion("mode =", value, "mode");
            return (Criteria) this;
        }

        public Criteria andModeNotEqualTo(Integer value) {
            addCriterion("mode <>", value, "mode");
            return (Criteria) this;
        }

        public Criteria andModeGreaterThan(Integer value) {
            addCriterion("mode >", value, "mode");
            return (Criteria) this;
        }

        public Criteria andModeGreaterThanOrEqualTo(Integer value) {
            addCriterion("mode >=", value, "mode");
            return (Criteria) this;
        }

        public Criteria andModeLessThan(Integer value) {
            addCriterion("mode <", value, "mode");
            return (Criteria) this;
        }

        public Criteria andModeLessThanOrEqualTo(Integer value) {
            addCriterion("mode <=", value, "mode");
            return (Criteria) this;
        }

        public Criteria andModeIn(List<Integer> values) {
            addCriterion("mode in", values, "mode");
            return (Criteria) this;
        }

        public Criteria andModeNotIn(List<Integer> values) {
            addCriterion("mode not in", values, "mode");
            return (Criteria) this;
        }

        public Criteria andModeBetween(Integer value1, Integer value2) {
            addCriterion("mode between", value1, value2, "mode");
            return (Criteria) this;
        }

        public Criteria andModeNotBetween(Integer value1, Integer value2) {
            addCriterion("mode not between", value1, value2, "mode");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table busi_game
     *
     * @mbg.generated do_not_delete_during_merge Mon May 15 08:36:44 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table busi_game
     *
     * @mbg.generated Mon May 15 08:36:44 CST 2017
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}