package game2peer.mybatis.domain;

import java.util.Date;

public class BusiGameLog {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column busi_game_log.id
	 * @mbg.generated  Mon May 08 11:10:07 CST 2017
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column busi_game_log.game_code
	 * @mbg.generated  Mon May 08 11:10:07 CST 2017
	 */
	private String gameCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column busi_game_log.create_time
	 * @mbg.generated  Mon May 08 11:10:07 CST 2017
	 */
	private Date createTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column busi_game_log.message
	 * @mbg.generated  Mon May 08 11:10:07 CST 2017
	 */
	private String message;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column busi_game_log.id
	 * @return  the value of busi_game_log.id
	 * @mbg.generated  Mon May 08 11:10:07 CST 2017
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column busi_game_log.id
	 * @param id  the value for busi_game_log.id
	 * @mbg.generated  Mon May 08 11:10:07 CST 2017
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column busi_game_log.game_code
	 * @return  the value of busi_game_log.game_code
	 * @mbg.generated  Mon May 08 11:10:07 CST 2017
	 */
	public String getGameCode() {
		return gameCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column busi_game_log.game_code
	 * @param gameCode  the value for busi_game_log.game_code
	 * @mbg.generated  Mon May 08 11:10:07 CST 2017
	 */
	public void setGameCode(String gameCode) {
		this.gameCode = gameCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column busi_game_log.create_time
	 * @return  the value of busi_game_log.create_time
	 * @mbg.generated  Mon May 08 11:10:07 CST 2017
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column busi_game_log.create_time
	 * @param createTime  the value for busi_game_log.create_time
	 * @mbg.generated  Mon May 08 11:10:07 CST 2017
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column busi_game_log.message
	 * @return  the value of busi_game_log.message
	 * @mbg.generated  Mon May 08 11:10:07 CST 2017
	 */
	public String getMessage() {
		return message;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column busi_game_log.message
	 * @param message  the value for busi_game_log.message
	 * @mbg.generated  Mon May 08 11:10:07 CST 2017
	 */
	public void setMessage(String message) {
		this.message = message;
	}
}