package game2peer.mybatis.domain;

public class GlobalValue {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column global_value.g_key
	 * @mbg.generated  Wed May 10 12:03:08 CST 2017
	 */
	private String gKey;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column global_value.g_value
	 * @mbg.generated  Wed May 10 12:03:08 CST 2017
	 */
	private String gValue;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column global_value.description
	 * @mbg.generated  Wed May 10 12:03:08 CST 2017
	 */
	private String description;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column global_value.g_key
	 * @return  the value of global_value.g_key
	 * @mbg.generated  Wed May 10 12:03:08 CST 2017
	 */
	public String getgKey() {
		return gKey;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column global_value.g_key
	 * @param gKey  the value for global_value.g_key
	 * @mbg.generated  Wed May 10 12:03:08 CST 2017
	 */
	public void setgKey(String gKey) {
		this.gKey = gKey;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column global_value.g_value
	 * @return  the value of global_value.g_value
	 * @mbg.generated  Wed May 10 12:03:08 CST 2017
	 */
	public String getgValue() {
		return gValue;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column global_value.g_value
	 * @param gValue  the value for global_value.g_value
	 * @mbg.generated  Wed May 10 12:03:08 CST 2017
	 */
	public void setgValue(String gValue) {
		this.gValue = gValue;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column global_value.description
	 * @return  the value of global_value.description
	 * @mbg.generated  Wed May 10 12:03:08 CST 2017
	 */
	public String getDescription() {
		return description;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column global_value.description
	 * @param description  the value for global_value.description
	 * @mbg.generated  Wed May 10 12:03:08 CST 2017
	 */
	public void setDescription(String description) {
		this.description = description;
	}
}