package game2peer.mybatis.domain;

import java.math.BigDecimal;

public class GroupUrl {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column group_url.group_id
     *
     * @mbg.generated Thu Mar 30 08:58:31 CST 2017
     */
    private Integer groupId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column group_url.url
     *
     * @mbg.generated Thu Mar 30 08:58:31 CST 2017
     */
    private String url;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column group_url.get
     *
     * @mbg.generated Thu Mar 30 08:58:31 CST 2017
     */
    private BigDecimal get;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column group_url.put
     *
     * @mbg.generated Thu Mar 30 08:58:31 CST 2017
     */
    private BigDecimal put;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column group_url.del
     *
     * @mbg.generated Thu Mar 30 08:58:31 CST 2017
     */
    private BigDecimal del;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column group_url.modi
     *
     * @mbg.generated Thu Mar 30 08:58:31 CST 2017
     */
    private BigDecimal modi;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column group_url.group_id
     *
     * @return the value of group_url.group_id
     *
     * @mbg.generated Thu Mar 30 08:58:31 CST 2017
     */
    public Integer getGroupId() {
        return groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column group_url.group_id
     *
     * @param groupId the value for group_url.group_id
     *
     * @mbg.generated Thu Mar 30 08:58:31 CST 2017
     */
    public void setGroupId(Integer groupId) {
        this.groupId = groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column group_url.url
     *
     * @return the value of group_url.url
     *
     * @mbg.generated Thu Mar 30 08:58:31 CST 2017
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column group_url.url
     *
     * @param url the value for group_url.url
     *
     * @mbg.generated Thu Mar 30 08:58:31 CST 2017
     */
    public void setUrl(String url) {
        this.url = url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column group_url.get
     *
     * @return the value of group_url.get
     *
     * @mbg.generated Thu Mar 30 08:58:31 CST 2017
     */
    public BigDecimal getGet() {
        return get;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column group_url.get
     *
     * @param get the value for group_url.get
     *
     * @mbg.generated Thu Mar 30 08:58:31 CST 2017
     */
    public void setGet(BigDecimal get) {
        this.get = get;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column group_url.put
     *
     * @return the value of group_url.put
     *
     * @mbg.generated Thu Mar 30 08:58:31 CST 2017
     */
    public BigDecimal getPut() {
        return put;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column group_url.put
     *
     * @param put the value for group_url.put
     *
     * @mbg.generated Thu Mar 30 08:58:31 CST 2017
     */
    public void setPut(BigDecimal put) {
        this.put = put;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column group_url.del
     *
     * @return the value of group_url.del
     *
     * @mbg.generated Thu Mar 30 08:58:31 CST 2017
     */
    public BigDecimal getDel() {
        return del;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column group_url.del
     *
     * @param del the value for group_url.del
     *
     * @mbg.generated Thu Mar 30 08:58:31 CST 2017
     */
    public void setDel(BigDecimal del) {
        this.del = del;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column group_url.modi
     *
     * @return the value of group_url.modi
     *
     * @mbg.generated Thu Mar 30 08:58:31 CST 2017
     */
    public BigDecimal getModi() {
        return modi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column group_url.modi
     *
     * @param modi the value for group_url.modi
     *
     * @mbg.generated Thu Mar 30 08:58:31 CST 2017
     */
    public void setModi(BigDecimal modi) {
        this.modi = modi;
    }
}