package game2peer.mybatis.domain;

public class GroupUrl {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column group_url.group_id
	 * @mbg.generated  Tue May 09 16:05:21 CST 2017
	 */
	private Integer groupId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column group_url.url
	 * @mbg.generated  Tue May 09 16:05:21 CST 2017
	 */
	private String url;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column group_url.get
	 * @mbg.generated  Tue May 09 16:05:21 CST 2017
	 */
	private Integer get;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column group_url.put
	 * @mbg.generated  Tue May 09 16:05:21 CST 2017
	 */
	private Integer put;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column group_url.del
	 * @mbg.generated  Tue May 09 16:05:21 CST 2017
	 */
	private Integer del;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column group_url.modi
	 * @mbg.generated  Tue May 09 16:05:21 CST 2017
	 */
	private Integer modi;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column group_url.oper
	 * @mbg.generated  Tue May 09 16:05:21 CST 2017
	 */
	private Integer oper;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column group_url.group_id
	 * @return  the value of group_url.group_id
	 * @mbg.generated  Tue May 09 16:05:21 CST 2017
	 */
	public Integer getGroupId() {
		return groupId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column group_url.group_id
	 * @param groupId  the value for group_url.group_id
	 * @mbg.generated  Tue May 09 16:05:21 CST 2017
	 */
	public void setGroupId(Integer groupId) {
		this.groupId = groupId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column group_url.url
	 * @return  the value of group_url.url
	 * @mbg.generated  Tue May 09 16:05:21 CST 2017
	 */
	public String getUrl() {
		return url;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column group_url.url
	 * @param url  the value for group_url.url
	 * @mbg.generated  Tue May 09 16:05:21 CST 2017
	 */
	public void setUrl(String url) {
		this.url = url;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column group_url.get
	 * @return  the value of group_url.get
	 * @mbg.generated  Tue May 09 16:05:21 CST 2017
	 */
	public Integer getGet() {
		return get;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column group_url.get
	 * @param get  the value for group_url.get
	 * @mbg.generated  Tue May 09 16:05:21 CST 2017
	 */
	public void setGet(Integer get) {
		this.get = get;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column group_url.put
	 * @return  the value of group_url.put
	 * @mbg.generated  Tue May 09 16:05:21 CST 2017
	 */
	public Integer getPut() {
		return put;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column group_url.put
	 * @param put  the value for group_url.put
	 * @mbg.generated  Tue May 09 16:05:21 CST 2017
	 */
	public void setPut(Integer put) {
		this.put = put;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column group_url.del
	 * @return  the value of group_url.del
	 * @mbg.generated  Tue May 09 16:05:21 CST 2017
	 */
	public Integer getDel() {
		return del;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column group_url.del
	 * @param del  the value for group_url.del
	 * @mbg.generated  Tue May 09 16:05:21 CST 2017
	 */
	public void setDel(Integer del) {
		this.del = del;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column group_url.modi
	 * @return  the value of group_url.modi
	 * @mbg.generated  Tue May 09 16:05:21 CST 2017
	 */
	public Integer getModi() {
		return modi;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column group_url.modi
	 * @param modi  the value for group_url.modi
	 * @mbg.generated  Tue May 09 16:05:21 CST 2017
	 */
	public void setModi(Integer modi) {
		this.modi = modi;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column group_url.oper
	 * @return  the value of group_url.oper
	 * @mbg.generated  Tue May 09 16:05:21 CST 2017
	 */
	public Integer getOper() {
		return oper;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column group_url.oper
	 * @param oper  the value for group_url.oper
	 * @mbg.generated  Tue May 09 16:05:21 CST 2017
	 */
	public void setOper(Integer oper) {
		this.oper = oper;
	}
}