package game2peer.mybatis.domain;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

public class GroupUrlExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table group_url
     *
     * @mbg.generated Thu Mar 30 08:58:31 CST 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table group_url
     *
     * @mbg.generated Thu Mar 30 08:58:31 CST 2017
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table group_url
     *
     * @mbg.generated Thu Mar 30 08:58:31 CST 2017
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_url
     *
     * @mbg.generated Thu Mar 30 08:58:31 CST 2017
     */
    public GroupUrlExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_url
     *
     * @mbg.generated Thu Mar 30 08:58:31 CST 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_url
     *
     * @mbg.generated Thu Mar 30 08:58:31 CST 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_url
     *
     * @mbg.generated Thu Mar 30 08:58:31 CST 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_url
     *
     * @mbg.generated Thu Mar 30 08:58:31 CST 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_url
     *
     * @mbg.generated Thu Mar 30 08:58:31 CST 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_url
     *
     * @mbg.generated Thu Mar 30 08:58:31 CST 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_url
     *
     * @mbg.generated Thu Mar 30 08:58:31 CST 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_url
     *
     * @mbg.generated Thu Mar 30 08:58:31 CST 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_url
     *
     * @mbg.generated Thu Mar 30 08:58:31 CST 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_url
     *
     * @mbg.generated Thu Mar 30 08:58:31 CST 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table group_url
     *
     * @mbg.generated Thu Mar 30 08:58:31 CST 2017
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andGroupIdIsNull() {
            addCriterion("group_id is null");
            return (Criteria) this;
        }

        public Criteria andGroupIdIsNotNull() {
            addCriterion("group_id is not null");
            return (Criteria) this;
        }

        public Criteria andGroupIdEqualTo(Integer value) {
            addCriterion("group_id =", value, "groupId");
            return (Criteria) this;
        }

        public Criteria andGroupIdNotEqualTo(Integer value) {
            addCriterion("group_id <>", value, "groupId");
            return (Criteria) this;
        }

        public Criteria andGroupIdGreaterThan(Integer value) {
            addCriterion("group_id >", value, "groupId");
            return (Criteria) this;
        }

        public Criteria andGroupIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("group_id >=", value, "groupId");
            return (Criteria) this;
        }

        public Criteria andGroupIdLessThan(Integer value) {
            addCriterion("group_id <", value, "groupId");
            return (Criteria) this;
        }

        public Criteria andGroupIdLessThanOrEqualTo(Integer value) {
            addCriterion("group_id <=", value, "groupId");
            return (Criteria) this;
        }

        public Criteria andGroupIdIn(List<Integer> values) {
            addCriterion("group_id in", values, "groupId");
            return (Criteria) this;
        }

        public Criteria andGroupIdNotIn(List<Integer> values) {
            addCriterion("group_id not in", values, "groupId");
            return (Criteria) this;
        }

        public Criteria andGroupIdBetween(Integer value1, Integer value2) {
            addCriterion("group_id between", value1, value2, "groupId");
            return (Criteria) this;
        }

        public Criteria andGroupIdNotBetween(Integer value1, Integer value2) {
            addCriterion("group_id not between", value1, value2, "groupId");
            return (Criteria) this;
        }

        public Criteria andUrlIsNull() {
            addCriterion("url is null");
            return (Criteria) this;
        }

        public Criteria andUrlIsNotNull() {
            addCriterion("url is not null");
            return (Criteria) this;
        }

        public Criteria andUrlEqualTo(String value) {
            addCriterion("url =", value, "url");
            return (Criteria) this;
        }

        public Criteria andUrlNotEqualTo(String value) {
            addCriterion("url <>", value, "url");
            return (Criteria) this;
        }

        public Criteria andUrlGreaterThan(String value) {
            addCriterion("url >", value, "url");
            return (Criteria) this;
        }

        public Criteria andUrlGreaterThanOrEqualTo(String value) {
            addCriterion("url >=", value, "url");
            return (Criteria) this;
        }

        public Criteria andUrlLessThan(String value) {
            addCriterion("url <", value, "url");
            return (Criteria) this;
        }

        public Criteria andUrlLessThanOrEqualTo(String value) {
            addCriterion("url <=", value, "url");
            return (Criteria) this;
        }

        public Criteria andUrlLike(String value) {
            addCriterion("url like", value, "url");
            return (Criteria) this;
        }

        public Criteria andUrlNotLike(String value) {
            addCriterion("url not like", value, "url");
            return (Criteria) this;
        }

        public Criteria andUrlIn(List<String> values) {
            addCriterion("url in", values, "url");
            return (Criteria) this;
        }

        public Criteria andUrlNotIn(List<String> values) {
            addCriterion("url not in", values, "url");
            return (Criteria) this;
        }

        public Criteria andUrlBetween(String value1, String value2) {
            addCriterion("url between", value1, value2, "url");
            return (Criteria) this;
        }

        public Criteria andUrlNotBetween(String value1, String value2) {
            addCriterion("url not between", value1, value2, "url");
            return (Criteria) this;
        }

        public Criteria andGetIsNull() {
            addCriterion("get is null");
            return (Criteria) this;
        }

        public Criteria andGetIsNotNull() {
            addCriterion("get is not null");
            return (Criteria) this;
        }

        public Criteria andGetEqualTo(BigDecimal value) {
            addCriterion("get =", value, "get");
            return (Criteria) this;
        }

        public Criteria andGetNotEqualTo(BigDecimal value) {
            addCriterion("get <>", value, "get");
            return (Criteria) this;
        }

        public Criteria andGetGreaterThan(BigDecimal value) {
            addCriterion("get >", value, "get");
            return (Criteria) this;
        }

        public Criteria andGetGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("get >=", value, "get");
            return (Criteria) this;
        }

        public Criteria andGetLessThan(BigDecimal value) {
            addCriterion("get <", value, "get");
            return (Criteria) this;
        }

        public Criteria andGetLessThanOrEqualTo(BigDecimal value) {
            addCriterion("get <=", value, "get");
            return (Criteria) this;
        }

        public Criteria andGetIn(List<BigDecimal> values) {
            addCriterion("get in", values, "get");
            return (Criteria) this;
        }

        public Criteria andGetNotIn(List<BigDecimal> values) {
            addCriterion("get not in", values, "get");
            return (Criteria) this;
        }

        public Criteria andGetBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("get between", value1, value2, "get");
            return (Criteria) this;
        }

        public Criteria andGetNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("get not between", value1, value2, "get");
            return (Criteria) this;
        }

        public Criteria andPutIsNull() {
            addCriterion("put is null");
            return (Criteria) this;
        }

        public Criteria andPutIsNotNull() {
            addCriterion("put is not null");
            return (Criteria) this;
        }

        public Criteria andPutEqualTo(BigDecimal value) {
            addCriterion("put =", value, "put");
            return (Criteria) this;
        }

        public Criteria andPutNotEqualTo(BigDecimal value) {
            addCriterion("put <>", value, "put");
            return (Criteria) this;
        }

        public Criteria andPutGreaterThan(BigDecimal value) {
            addCriterion("put >", value, "put");
            return (Criteria) this;
        }

        public Criteria andPutGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("put >=", value, "put");
            return (Criteria) this;
        }

        public Criteria andPutLessThan(BigDecimal value) {
            addCriterion("put <", value, "put");
            return (Criteria) this;
        }

        public Criteria andPutLessThanOrEqualTo(BigDecimal value) {
            addCriterion("put <=", value, "put");
            return (Criteria) this;
        }

        public Criteria andPutIn(List<BigDecimal> values) {
            addCriterion("put in", values, "put");
            return (Criteria) this;
        }

        public Criteria andPutNotIn(List<BigDecimal> values) {
            addCriterion("put not in", values, "put");
            return (Criteria) this;
        }

        public Criteria andPutBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("put between", value1, value2, "put");
            return (Criteria) this;
        }

        public Criteria andPutNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("put not between", value1, value2, "put");
            return (Criteria) this;
        }

        public Criteria andDelIsNull() {
            addCriterion("del is null");
            return (Criteria) this;
        }

        public Criteria andDelIsNotNull() {
            addCriterion("del is not null");
            return (Criteria) this;
        }

        public Criteria andDelEqualTo(BigDecimal value) {
            addCriterion("del =", value, "del");
            return (Criteria) this;
        }

        public Criteria andDelNotEqualTo(BigDecimal value) {
            addCriterion("del <>", value, "del");
            return (Criteria) this;
        }

        public Criteria andDelGreaterThan(BigDecimal value) {
            addCriterion("del >", value, "del");
            return (Criteria) this;
        }

        public Criteria andDelGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("del >=", value, "del");
            return (Criteria) this;
        }

        public Criteria andDelLessThan(BigDecimal value) {
            addCriterion("del <", value, "del");
            return (Criteria) this;
        }

        public Criteria andDelLessThanOrEqualTo(BigDecimal value) {
            addCriterion("del <=", value, "del");
            return (Criteria) this;
        }

        public Criteria andDelIn(List<BigDecimal> values) {
            addCriterion("del in", values, "del");
            return (Criteria) this;
        }

        public Criteria andDelNotIn(List<BigDecimal> values) {
            addCriterion("del not in", values, "del");
            return (Criteria) this;
        }

        public Criteria andDelBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("del between", value1, value2, "del");
            return (Criteria) this;
        }

        public Criteria andDelNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("del not between", value1, value2, "del");
            return (Criteria) this;
        }

        public Criteria andModiIsNull() {
            addCriterion("modi is null");
            return (Criteria) this;
        }

        public Criteria andModiIsNotNull() {
            addCriterion("modi is not null");
            return (Criteria) this;
        }

        public Criteria andModiEqualTo(BigDecimal value) {
            addCriterion("modi =", value, "modi");
            return (Criteria) this;
        }

        public Criteria andModiNotEqualTo(BigDecimal value) {
            addCriterion("modi <>", value, "modi");
            return (Criteria) this;
        }

        public Criteria andModiGreaterThan(BigDecimal value) {
            addCriterion("modi >", value, "modi");
            return (Criteria) this;
        }

        public Criteria andModiGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("modi >=", value, "modi");
            return (Criteria) this;
        }

        public Criteria andModiLessThan(BigDecimal value) {
            addCriterion("modi <", value, "modi");
            return (Criteria) this;
        }

        public Criteria andModiLessThanOrEqualTo(BigDecimal value) {
            addCriterion("modi <=", value, "modi");
            return (Criteria) this;
        }

        public Criteria andModiIn(List<BigDecimal> values) {
            addCriterion("modi in", values, "modi");
            return (Criteria) this;
        }

        public Criteria andModiNotIn(List<BigDecimal> values) {
            addCriterion("modi not in", values, "modi");
            return (Criteria) this;
        }

        public Criteria andModiBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("modi between", value1, value2, "modi");
            return (Criteria) this;
        }

        public Criteria andModiNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("modi not between", value1, value2, "modi");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table group_url
     *
     * @mbg.generated do_not_delete_during_merge Thu Mar 30 08:58:31 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table group_url
     *
     * @mbg.generated Thu Mar 30 08:58:31 CST 2017
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}