package game2peer.mybatis.domain;

public class NavigationGroup {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column navigation_group.group_id
     *
     * @mbg.generated Mon May 15 08:36:44 CST 2017
     */
    private Integer groupId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column navigation_group.navigation_id
     *
     * @mbg.generated Mon May 15 08:36:44 CST 2017
     */
    private Integer navigationId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column navigation_group.description
     *
     * @mbg.generated Mon May 15 08:36:44 CST 2017
     */
    private String description;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column navigation_group.group_id
     *
     * @return the value of navigation_group.group_id
     *
     * @mbg.generated Mon May 15 08:36:44 CST 2017
     */
    public Integer getGroupId() {
        return groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column navigation_group.group_id
     *
     * @param groupId the value for navigation_group.group_id
     *
     * @mbg.generated Mon May 15 08:36:44 CST 2017
     */
    public void setGroupId(Integer groupId) {
        this.groupId = groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column navigation_group.navigation_id
     *
     * @return the value of navigation_group.navigation_id
     *
     * @mbg.generated Mon May 15 08:36:44 CST 2017
     */
    public Integer getNavigationId() {
        return navigationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column navigation_group.navigation_id
     *
     * @param navigationId the value for navigation_group.navigation_id
     *
     * @mbg.generated Mon May 15 08:36:44 CST 2017
     */
    public void setNavigationId(Integer navigationId) {
        this.navigationId = navigationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column navigation_group.description
     *
     * @return the value of navigation_group.description
     *
     * @mbg.generated Mon May 15 08:36:44 CST 2017
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column navigation_group.description
     *
     * @param description the value for navigation_group.description
     *
     * @mbg.generated Mon May 15 08:36:44 CST 2017
     */
    public void setDescription(String description) {
        this.description = description;
    }
}