package game2peer.mybatis.domain;

public class Pages {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pages.id
     *
     * @mbg.generated Mon May 15 08:36:44 CST 2017
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pages.title
     *
     * @mbg.generated Mon May 15 08:36:44 CST 2017
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pages.layout_template
     *
     * @mbg.generated Mon May 15 08:36:44 CST 2017
     */
    private String layoutTemplate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pages.content_page
     *
     * @mbg.generated Mon May 15 08:36:44 CST 2017
     */
    private String contentPage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pages.bean
     *
     * @mbg.generated Mon May 15 08:36:44 CST 2017
     */
    private String bean;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pages.id
     *
     * @return the value of pages.id
     *
     * @mbg.generated Mon May 15 08:36:44 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pages.id
     *
     * @param id the value for pages.id
     *
     * @mbg.generated Mon May 15 08:36:44 CST 2017
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pages.title
     *
     * @return the value of pages.title
     *
     * @mbg.generated Mon May 15 08:36:44 CST 2017
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pages.title
     *
     * @param title the value for pages.title
     *
     * @mbg.generated Mon May 15 08:36:44 CST 2017
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pages.layout_template
     *
     * @return the value of pages.layout_template
     *
     * @mbg.generated Mon May 15 08:36:44 CST 2017
     */
    public String getLayoutTemplate() {
        return layoutTemplate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pages.layout_template
     *
     * @param layoutTemplate the value for pages.layout_template
     *
     * @mbg.generated Mon May 15 08:36:44 CST 2017
     */
    public void setLayoutTemplate(String layoutTemplate) {
        this.layoutTemplate = layoutTemplate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pages.content_page
     *
     * @return the value of pages.content_page
     *
     * @mbg.generated Mon May 15 08:36:44 CST 2017
     */
    public String getContentPage() {
        return contentPage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pages.content_page
     *
     * @param contentPage the value for pages.content_page
     *
     * @mbg.generated Mon May 15 08:36:44 CST 2017
     */
    public void setContentPage(String contentPage) {
        this.contentPage = contentPage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pages.bean
     *
     * @return the value of pages.bean
     *
     * @mbg.generated Mon May 15 08:36:44 CST 2017
     */
    public String getBean() {
        return bean;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pages.bean
     *
     * @param bean the value for pages.bean
     *
     * @mbg.generated Mon May 15 08:36:44 CST 2017
     */
    public void setBean(String bean) {
        this.bean = bean;
    }
}