package game2peer.mybatis.domain;

public class RestApis {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rest_apis.id
     *
     * @mbg.generated Mon May 08 11:10:07 CST 2017
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rest_apis.bean
     *
     * @mbg.generated Mon May 08 11:10:07 CST 2017
     */
    private String bean;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rest_apis.crf_enable
     *
     * @mbg.generated Mon May 08 11:10:07 CST 2017
     */
    private Integer crfEnable;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rest_apis.id
     *
     * @return the value of rest_apis.id
     *
     * @mbg.generated Mon May 08 11:10:07 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rest_apis.id
     *
     * @param id the value for rest_apis.id
     *
     * @mbg.generated Mon May 08 11:10:07 CST 2017
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rest_apis.bean
     *
     * @return the value of rest_apis.bean
     *
     * @mbg.generated Mon May 08 11:10:07 CST 2017
     */
    public String getBean() {
        return bean;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rest_apis.bean
     *
     * @param bean the value for rest_apis.bean
     *
     * @mbg.generated Mon May 08 11:10:07 CST 2017
     */
    public void setBean(String bean) {
        this.bean = bean;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rest_apis.crf_enable
     *
     * @return the value of rest_apis.crf_enable
     *
     * @mbg.generated Mon May 08 11:10:07 CST 2017
     */
    public Integer getCrfEnable() {
        return crfEnable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rest_apis.crf_enable
     *
     * @param crfEnable the value for rest_apis.crf_enable
     *
     * @mbg.generated Mon May 08 11:10:07 CST 2017
     */
    public void setCrfEnable(Integer crfEnable) {
        this.crfEnable = crfEnable;
    }
}