package game2peer.mybatis.domain;

public class RoleUrl extends RoleUrlKey {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column role_url.description
	 * @mbg.generated  Thu Mar 30 08:58:31 CST 2017
	 */
	private String description;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column role_url.get
	 * @mbg.generated  Thu Mar 30 08:58:31 CST 2017
	 */
	private Integer get;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column role_url.put
	 * @mbg.generated  Thu Mar 30 08:58:31 CST 2017
	 */
	private Integer put;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column role_url.del
	 * @mbg.generated  Thu Mar 30 08:58:31 CST 2017
	 */
	private Integer del;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column role_url.modi
	 * @mbg.generated  Thu Mar 30 08:58:31 CST 2017
	 */
	private Integer modi;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column role_url.description
	 * @return  the value of role_url.description
	 * @mbg.generated  Thu Mar 30 08:58:31 CST 2017
	 */
	public String getDescription() {
		return description;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column role_url.description
	 * @param description  the value for role_url.description
	 * @mbg.generated  Thu Mar 30 08:58:31 CST 2017
	 */
	public void setDescription(String description) {
		this.description = description;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column role_url.get
	 * @return  the value of role_url.get
	 * @mbg.generated  Thu Mar 30 08:58:31 CST 2017
	 */
	public Integer getGet() {
		return get;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column role_url.get
	 * @param get  the value for role_url.get
	 * @mbg.generated  Thu Mar 30 08:58:31 CST 2017
	 */
	public void setGet(Integer get) {
		this.get = get;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column role_url.put
	 * @return  the value of role_url.put
	 * @mbg.generated  Thu Mar 30 08:58:31 CST 2017
	 */
	public Integer getPut() {
		return put;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column role_url.put
	 * @param put  the value for role_url.put
	 * @mbg.generated  Thu Mar 30 08:58:31 CST 2017
	 */
	public void setPut(Integer put) {
		this.put = put;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column role_url.del
	 * @return  the value of role_url.del
	 * @mbg.generated  Thu Mar 30 08:58:31 CST 2017
	 */
	public Integer getDel() {
		return del;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column role_url.del
	 * @param del  the value for role_url.del
	 * @mbg.generated  Thu Mar 30 08:58:31 CST 2017
	 */
	public void setDel(Integer del) {
		this.del = del;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column role_url.modi
	 * @return  the value of role_url.modi
	 * @mbg.generated  Thu Mar 30 08:58:31 CST 2017
	 */
	public Integer getModi() {
		return modi;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column role_url.modi
	 * @param modi  the value for role_url.modi
	 * @mbg.generated  Thu Mar 30 08:58:31 CST 2017
	 */
	public void setModi(Integer modi) {
		this.modi = modi;
	}
}