package game2peer.mybatis.domain;

import java.util.Date;

public class User {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.id
     *
     * @mbg.generated Mon May 15 08:36:44 CST 2017
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.login_name
     *
     * @mbg.generated Mon May 15 08:36:44 CST 2017
     */
    private String loginName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.nice_name
     *
     * @mbg.generated Mon May 15 08:36:44 CST 2017
     */
    private String niceName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.password
     *
     * @mbg.generated Mon May 15 08:36:44 CST 2017
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.group_id
     *
     * @mbg.generated Mon May 15 08:36:44 CST 2017
     */
    private Integer groupId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.actived
     *
     * @mbg.generated Mon May 15 08:36:44 CST 2017
     */
    private String actived;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.create_time
     *
     * @mbg.generated Mon May 15 08:36:44 CST 2017
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.denied
     *
     * @mbg.generated Mon May 15 08:36:44 CST 2017
     */
    private String denied;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.id
     *
     * @return the value of user.id
     *
     * @mbg.generated Mon May 15 08:36:44 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.id
     *
     * @param id the value for user.id
     *
     * @mbg.generated Mon May 15 08:36:44 CST 2017
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.login_name
     *
     * @return the value of user.login_name
     *
     * @mbg.generated Mon May 15 08:36:44 CST 2017
     */
    public String getLoginName() {
        return loginName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.login_name
     *
     * @param loginName the value for user.login_name
     *
     * @mbg.generated Mon May 15 08:36:44 CST 2017
     */
    public void setLoginName(String loginName) {
        this.loginName = loginName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.nice_name
     *
     * @return the value of user.nice_name
     *
     * @mbg.generated Mon May 15 08:36:44 CST 2017
     */
    public String getNiceName() {
        return niceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.nice_name
     *
     * @param niceName the value for user.nice_name
     *
     * @mbg.generated Mon May 15 08:36:44 CST 2017
     */
    public void setNiceName(String niceName) {
        this.niceName = niceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.password
     *
     * @return the value of user.password
     *
     * @mbg.generated Mon May 15 08:36:44 CST 2017
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.password
     *
     * @param password the value for user.password
     *
     * @mbg.generated Mon May 15 08:36:44 CST 2017
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.group_id
     *
     * @return the value of user.group_id
     *
     * @mbg.generated Mon May 15 08:36:44 CST 2017
     */
    public Integer getGroupId() {
        return groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.group_id
     *
     * @param groupId the value for user.group_id
     *
     * @mbg.generated Mon May 15 08:36:44 CST 2017
     */
    public void setGroupId(Integer groupId) {
        this.groupId = groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.actived
     *
     * @return the value of user.actived
     *
     * @mbg.generated Mon May 15 08:36:44 CST 2017
     */
    public String getActived() {
        return actived;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.actived
     *
     * @param actived the value for user.actived
     *
     * @mbg.generated Mon May 15 08:36:44 CST 2017
     */
    public void setActived(String actived) {
        this.actived = actived;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.create_time
     *
     * @return the value of user.create_time
     *
     * @mbg.generated Mon May 15 08:36:44 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.create_time
     *
     * @param createTime the value for user.create_time
     *
     * @mbg.generated Mon May 15 08:36:44 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.denied
     *
     * @return the value of user.denied
     *
     * @mbg.generated Mon May 15 08:36:44 CST 2017
     */
    public String getDenied() {
        return denied;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.denied
     *
     * @param denied the value for user.denied
     *
     * @mbg.generated Mon May 15 08:36:44 CST 2017
     */
    public void setDenied(String denied) {
        this.denied = denied;
    }
}