package game2peer.mybatis.domain;

public class UserGroup {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_group.id
     *
     * @mbg.generated Tue Mar 28 12:27:59 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_group.description
     *
     * @mbg.generated Tue Mar 28 12:27:59 CST 2017
     */
    private String description;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_group.id
     *
     * @return the value of user_group.id
     *
     * @mbg.generated Tue Mar 28 12:27:59 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_group.id
     *
     * @param id the value for user_group.id
     *
     * @mbg.generated Tue Mar 28 12:27:59 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_group.description
     *
     * @return the value of user_group.description
     *
     * @mbg.generated Tue Mar 28 12:27:59 CST 2017
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_group.description
     *
     * @param description the value for user_group.description
     *
     * @mbg.generated Tue Mar 28 12:27:59 CST 2017
     */
    public void setDescription(String description) {
        this.description = description;
    }
}